### PR TITLE
Initializes website

### PR DESCRIPTION
**Pull request by ultimaweapon**
This will be replaced our current website at https://obliteration.net. This website will contains:

- A beautiful landing page similar to https://squidfunk.github.io/mkdocs-material. My idea is we will ask Mr. Snowy to help with this since he are the one who built the current version.
- A user guide.
- A developer guide. See #834 for the discussion about this.
- A compatibility list.

### CODE REVIEW

**Comment by VocalFan** [comment]
Dude... Snowy is still working on the base site. It's just under a folder on the webaite .-.

**Comment by VocalFan** [comment]
And, once again, I REALLY don't approve this... Frankly... Bullshit amount of work for an issue that no other repo struggles with.

RPCS3 use the wiki no issue.
Ryujinx use the wiki no issue.
This, as far as I can see, is your little personal issue.

Which, I don't see why you're trying to make this more difficult than it has to be and it's beginning to annoy me greatly.

*If you've had personal drama in the past, cool, don't push it onto us.*

**Comment by ultimaweapon** [comment]
Please stop this kind of behavior. I already give you one more chance since I leaved from Matrix to not do a rude behavior.

**Comment by VocalFan** [comment]
I'm not wanting to be rude but when there is a simple thing and you make it into a more difficult thing when it doesn't have to be, it pains me ;w;

And Snowy is already working on the compatibility list/download page... I don't wanna just drop MORE on him mid-development x3

**Comment by VocalFan** [comment]
Like... I'm the one who paid for the PC hardware for the server and paid for development of the website -w-;
If I were to try to have another page added, I'm sure that adds a cost .w.

**Comment by VocalFan** [comment]
Ultima, I love this project. I really do. But... You also have to respect other's opinions. Me, Acetone, SAFD... We agreed to a wiki... Which... Okay... I know you want the wiki to be a website page but... Just get that I paid for the website to be made out of my love for the project... Another page would be money out of my pocket. I want this project to grow but sometimes I feel like you want changes that instead stagger or distract development. And when I feel that way I kind of get upset because I want progress, not problems...

https://obliteration.net/gamma-boi/

Here's our wip version. Which if you notice in the top bar... We already had a Wiki button, which when pressed, brings you to the github wiki. Because... It just works. Table of contents, friendly formatting, supports light/dark mode, and is a common space to go for other Github programmers.

If you don't want any more, then I'll go for a bit, distract myself from... This.

**Comment by mikusp** [comment]
I don't see a reason why we cannot use a wiki, there's not that many of us involved, and until the project runs _anything_ I think our time would be better spent on development than bikeshedding where to put the compiling guide.

**Comment by ultimaweapon** [comment]
Then please focus on the issues.

The issue with Wiki is it cannot apply the same code review when someone edit the Wiki. As I told you in the previous discussion that I don't trust anyone on their own. There must be at least another people to approve the changes. I want Obliteration to be a project with transparency as much as possible and I don't want some kind of [XZ backdoor](https://en.wikipedia.org/wiki/XZ_Utils_backdoor) to be happen on the project that I'm still a leader. That mean "People use Wiki and nothing bad happen" cannot be used here. The only solution here is: How to apply a code review system to Wiki?

> Like... I'm the one who paid for the PC hardware for the server

Now you know one of the reason why I don't want to use your PC to run a CI. This new website will host on GitHub Page so we don't need your PC to run it anymore.

> and paid for development of the website 

I did not know about this before. I'm sorry to tell you that please stop this paid development. The same reason why I don't want to use your PC to run a CI.

> Ultima, I love this project. I really do.

Then you should know what I feel as a founder of this project.

> If you don't want any more, then I'll go for a bit, distract myself from... This.

The real problem here is it a paid development like I said on the above.

> I don't see a reason why we cannot use a wiki, there's not that many of us involved, and until the project runs _anything_ I think our time would be better spent on development than bikeshedding where to put the compiling guide.

See my second paragraph here. TLDR is I don't trust anyone on their own so it must be another people to approve the changes.

**Comment by VocalFan** [comment]
> Now you know one of the reason why I don't want to use your PC to run a CI. This new website will host on GitHub Page so we don't need your PC to run it anymore.

Wellllll... Compatibility page wouldn't work. Github Page only allows static sites.
Snowy already implemented the backend (written in rust :P) to read the Compatibility github page and make a database.
> I'm sorry to tell you that please stop this paid development.

 Nah. I'll... See if Snowy will add the Wiki page.

**Comment by VocalFan** [comment]
OKay uh @ultimaweapon Make a github repo for the website with me as a manager so I can add Snowy to it.

That way you can have your 'code review' and also contribute to the site if wanted.

**Comment by SuchAFuriousDeath** [comment]
> Snowy said Ugh. Idk what that means.
> 
> Meanwhile SAFD says "I don't wanna deal with this shit xD I have enough things in my life already"

To be clear, by "this shit" I mean this whole dispute, not one or the other side's position.

**Comment by ultimaweapon** [comment]
You guys have 4 choices here:

1. Find a solution for Wiki code review. AFAIK this is not possible that why I started this PR.
2. Approve this PR so we can apply the same code review system to the website content.
3. Revert back to a plain README as before.
4. Fork Obliteration so you have your own rules.

Both 2 and 3 will result in Wiki disabled permanently.

> OKay uh @ultimaweapon Make a github repo for the website with me as a manager so I can add Snowy to it.
> 
> That way you can have your 'code review' and also contribute to the site if wanted.

I'll not accept a paid development anymore so I refused.

**Comment by ultimaweapon** [comment]
> > I'll not accept a paid development anymore so I refused.
> 
> Uh, snowy isn't asking for any payment for the wiki page x3... _Actually, the only payment really done was for the backend development... As the compatibility database is a bit custom._

Here are the problems what you have proposed:

- It required a server to run. As I told you before that I try to avoid this.
- You and Mr. Snowy have a special relationship from a paid development before so it is useless to have you as a reviewer. It need to be someone else.

**Comment by VocalFan** [comment]
For point 1:

Sir, we kind of need that to even have a dynamic/non-static site. Besides... Cloudflare protection, plus firewall is blocked off besides the ports needed for the website. Along with that, any admin-related action requires a password that is lower, upper, numbers, and symbols.

Point 2:

I'm not wanting to add Snowy and be a reviewer for them. I just want to add them so they can add the website's code to the github repo XD.

**Comment by VocalFan** [comment]
The only special relationship me and snowy have is me calling him a nerd and him calling me one back lol.

**Comment by VocalFan** [comment]
@ultimaweapon Snowy seems to already have markdown to html generation working.

**Comment by ultimaweapon** [comment]
> Sir, we kind of need that to even have a dynamic/non-static site. Besides... Cloudflare protection, plus firewall is blocked off besides the ports needed for the website. Along with that, any admin-related action requires a password that is lower, upper, numbers, and symbols.

My solution in this PR don't need these things.

> I'm not wanting to add Snowy and be a reviewer for them. I just want to add them so they can add the website's code to the github repo XD.

Here: https://github.com/obhq/website

He need to create a PR there. He can add his name to `COPYING` if he want or change the license that is also a permissive license.

Once his PR merged I'll close this PR and disable the Wiki here.

**Comment by VocalFan** [comment]
@ultimaweapon Still wrong.

Compatibility page needs a DYNAMIC site with a backend to read the github page. Besides, Cloudflare works pretty well for user-to-user speed and security.

**Comment by VocalFan** [comment]
I get you want github pages, but one of the pages you asked for in this (the compatibility page) doesn't work with GH pages xD

**Comment by ultimaweapon** [comment]
If the website that Mr. Snowy is going to submit required a server to generate a dynamic content then I can't accept it.

> I get you want github pages, but one of the pages you asked for in this (the compatibility page) doesn't work with GH pages xD

My solution with this PR is will be the same as https://squidfunk.github.io/mkdocs-material that allow people to edit the page and submit a PR. This solution does not need a server to generate a dynamic content.

**Comment by VocalFan** [comment]
... Okay, bye. I'm just going to give up talking in this pull request as you overly worry about people trying to screw you over when you have all three other developers stressing over this.

Be mad at me, sure. But just know the other two developers aren't enjoying this interaction either. I mean, Mikusp already agreed with me, and SAFD is just disliking this conversation in general.

I've come to the point where even when the majority opposes a change, you seem hellbent on it being achieved. That doesn't mean it's a good change.

It's at the point that jokes are being made about this situation. Which made me realize... Yeah, this conversation is a joke. Why am I trying?

And, again, be mad at me as you like, but remember I'm also being based off other developers of this project feeling the same way.

**Comment by ultimaweapon** [comment]
No one enjoying this, not even me. Don't said like I'm the one who mad at you, you are the one who mad at me here. What I did here is I believed it is the right thing so if you guys think it is wrong, just fork it to have a new leader. Obliteration is an open-source project with license that does not forbid forking so you have the right to fork and working on it.

**Comment by VocalFan** [comment]
Okay, just... We don't want to lose you, but instead of being a leader... You're kind of being... Overly controlling over the rest of us? Yes, you should have a say in this... But so should your team! If everyone is opposing a change, then it most likely shouldn't be done.

**Comment by VocalFan** [comment]
https://obliteration.net/gamma-boi/wiki/home.html

**Comment by VocalFan** [comment]
The wiki has a commit history. If someone does become a bad actor, we can revert to an older revision and ban them. And stop saying that paying snowy means they have more privileges. No. At first, I wanted manager so I could add Snowy as a Collaborator for the website repo and that would be it. But using a pull request works just fine.

**Comment by SuchAFuriousDeath** [comment]
I'd just like to clarify that none of my statements should be interpreted as taking a side in this. I have to take a step back and think this through.

**Comment by VocalFan** [comment]
@SuchAFuriousDeath Which I tried to keep the tone that even though you picked no side, it's still a... Disturbance.

**Comment by ultimaweapon** [comment]
> The wiki has a commit history. If someone does become a bad actor, we can revert to an older revision and ban them.

When something bad happen it already too late. See XZ backdoor as an example.

> And stop saying that paying snowy means they have more privileges. No. At first, I wanted manager (for only the website repo) so I could add Snowy as a Collaborator for the website repo and that would be it. But using a pull request works just fine.

The real problem here is you just try to take advantage of the website being run on your machine and you have paid for website development. So I can't allow this kind of issue anymore.

**Comment by SuchAFuriousDeath** [comment]
> @SuchAFuriousDeath Which I tried to keep the tone that even though you picked no side, it's still a... Disturbance.

"If everyone is opposing a change, ..."

**Comment by VocalFan** [comment]
> https://obliteration.net/gamma-boi/wiki/home.html

But yeh, already got this :3

**Comment by ultimaweapon** [comment]
> Even if the wiki gets vandalized you can always roll it back because of the features that GitHub provides.

The problem is it unlikely to see if something bad happen until the damage has been spread. That why I said when something bad happen it already too late.

> In my honest opinion, having a website that isn't static is a good way of letting users check which games can be played. The website can also then be updated to fit the needs of the emulator.

The main problem here is not a dynamic VS static website. It is because someone need to pay to run it. Also the static site can have a search feature so it is really does need to be a dynamic website here.

> Later down the line when the emulator is a lot bigger and actually has people backing the project with money you can always choose to do something else.

I don't plan to accept any donations here. That why Obliteration does not have a funding button and it will never have.

**Comment by hax4dazy** [comment]
> The problem is it unlikely to see if something bad happen until the damage has been spread. That why I said when something bad happen it already too late.

How often do you think that'll happen? I mean, if we look at the [Ryujinx website](https://github.com/Ryujinx/Ryujinx-Website) they've never been vandalized. Neither has a project I've been running since 2020ish. I honestly don't see your point.

 > The main problem here is not a dynamic VS static website. It is because someone need to pay to run it. Also the static site can have a search feature so it is really does need to be a dynamic website here.

I don't think Vocal said he wanted to be paid. At least, from reading this entire pull request, he paid for the website / back-end of the website out of his own pocket. He bought his own hardware / server and is hosting that himself. While yeah, his network might go down which will pull the site down for a while, you could always move the whole operation to a really cheap VPS or even have people on standby to "take over" if their network / server does go down. Hell, even I would volunteer as being someone that could "take over" the website hosting if theirs goes down. I've already got several sites hosted on my server running at home and I have the infrastructure / knowledge for hosting.

**Comment by VocalFan** [comment]
And to be honest, the server is using my old motherboard, case, and GPU. Only thing I had to buy was the CPU and PSU.

**Comment by VocalFan** [comment]
@hax4dazy As for the server going down, I actually just got a UPS for this! Lasts a good hour without any power.

**Comment by ultimaweapon** [comment]
> How often do you think that'll happen? I mean, if we look at the [Ryujinx website](https://github.com/Ryujinx/Ryujinx-Website) they've never been vandalized. Neither has a project I've been running since 2020ish. I honestly don't see your point.

As I said above that I don't trust anyone so "People does not have this problem" is not a valid reason for me to allow unreviewed Wiki here.

> I don't think Vocal said he wanted to be paid. At least, from reading this entire pull request, he paid for the website / back-end of the website out of his own pocket. He bought his own hardware / server and is hosting that himself. While yeah, his network might go down which will pull the site down for a while, you could always move the whole operation to a really cheap VPS or even have people on standby to "take over" if their network / server does go down. Hell, even I would volunteer as being someone that could "take over" the website hosting if theirs goes down. I've already got several sites hosted on my server running at home and I have the infrastructure / knowledge for hosting.

The problem is not because he asked for paid, it is because he try to take advantage of it. Please read from beginning before judging anything here.

**Comment by VocalFan** [comment]
Take advantage of what? I mean all I wanted was just to make it so Snowy could be a collaborator for the Website repo and only that repo. Like how we're all technically collaborators for the entire project.

**Comment by VocalFan** [comment]
Even if he is a collaborator, he still would need the approval process done.

**Comment by ultimaweapon** [comment]
Screenshot 2024-04-16 at 21-05-20 Initializes website by ultimaweapon · Pull Request #840 · obhq_obliteration

**Comment by VocalFan** [comment]
That was more about just you saying I was rude when I put time and love into this project just for it to be blown off and dismissed x3

**Comment by hax4dazy** [comment]
> The problem is not because he asked for paid, it is because he try to take advantage of it. Please read from beginning before judging anything here.

You can just say that you don't trust vocal, if that's all you want to say then go for it. 

> As I said above that I don't trust anyone so "People does not have this problem" is not a valid reason for me to allow unreviewed Wiki here.

Alright fair enough, I know of ONE wiki that had this issue before. But they have webhook's setup in a quite large server which is monitored by a lot of people. If anything were to happen someone can instantly notify one of the admins and have them fix it. 
If you have any issues with vocal hosting the website himself you could always ask for login credentials to that server. That way you could also monitor and see what is going on.

**Comment by ultimaweapon** [comment]
> That was more about just you saying I was rude when I put time and love into this project just for it to be blown off and dismissed x3

It does not matter as long as your reason is because you paid for it. That why I don't want anyone to paid for anything so no one can use this fact to have advantage over the other member.

> You can just say that you don't trust vocal, if that's all you want to say then go for it.

I don't trust anyone. If anyone trying the same thing the response from me will be the same.

I'll lock the comment for now otherwise this PR will be endless. If anyone want to discus more on this issue, please read from the beginning to understand the whole situation then you can start a new discussion about this at https://github.com/obhq/obliteration/discussions

**Comment by VocalFan** [comment]
@ultimaweapon Hold off on this, alright? Snowy might try to make the site GH pages compatible.

**Comment by ultimaweapon** [comment]
The development of website will be continue at https://github.com/obhq/website.

**Pull request closed without merging**
