### PR TITLE
First try to read file, then create file if it doesn't exist.

### LINKED ISSUE #773: Fix raw_mkdir broken on Windows
Introduced by #772.

### PR DESCRIPTION
**Pull request by VocalFan**
Fix to SuchAFuriousDeath having the fix be half-right.

Is kind of unclean, but the best we have for now. Tested to handle folders existing and not existing just fine.

Fixes #773

### CODE REVIEW

**Comment by ultimaweapon** [comment]
This is not correct because it will cause behavior different from `raw_mkdir` on *nix. See https://github.com/obhq/obliteration/pull/772#issuecomment-2022144486 for more details.

**Comment by VocalFan** [comment]
Ya say that, yet this still seems to give results :P

I mean, we reach the todo'd open function now... Instead of just erroring. Even then if the folders already existed, file_open wouldn't error and we'd reach Open anyways. But no, windows doesn't like having one type where it `if file exists, read it, if not, make then read it.` You have to do both.

**Comment by SuchAFuriousDeath** [comment]
That's not true, 
image

**Comment by VocalFan** [comment]
> That's not true, image

...Damn, I'll redo this then lmao-

**Comment by SuchAFuriousDeath** [comment]
It will still be wrong

**Pull request closed without merging**
