### PR TITLE
Resolves symbol for non-PLT relocations

### LINKED ISSUE #253: Syscall 599: Relocation type 6 is not supported
This error happens on both Amplitude and Project Diva X.

Amplitude log: [amplog.txt](https://github.com/obhq/obliteration/files/12043800/amplog.txt)
Project Diva X: [PDXlog.txt](https://github.com/obhq/obliteration/files/12043801/PDXlog.txt)

### PR DESCRIPTION
**Pull request by ultimaweapon**
Fixes #253.

### CODE REVIEW

**Comment by VocalFan** [comment]
For some reason, Linux builds are getting stuck on the Qt install, just had that happen on my Obliteration repository as well! Either way, I'll test this when I get home.

**Comment by VocalFan** [comment]
Yeah, you kinda have to just retry until it works

**Comment by VocalFan** [comment]
From my list earlier:

1. Syscall 599 Reloc 6
The Division
Amplitude
Mighty No. 9
Project Diva X

-----

All games now are a part of issue #302

**Comment by ultimaweapon** [comment]
Seems like we need to move from https://github.com/jurplel/install-qt-action. Have too many problems recently.

**Comment by VocalFan** [comment]
> Seems like we need to move from https://github.com/jurplel/install-qt-action. Have too many problems recently.

Looking into it, it seems like the servers that the Github Linux uses could be bugging out. Other repos are having issues with other packages.

**Pull request merged**
