### PR TITLE
Several Advancements

### PR DESCRIPTION
**Pull request by SuchAFuriousDeath**
Partial implementation of #428 (to the point where it allows us to go further), stubbed #416 and the newly reachable syscalls.
I also added a table of sysctls for a better overview and easier searching in the future.

UPDATE: also added a near-complete implementation of syscall 649

### CODE REVIEW

**Comment by SuchAFuriousDeath** [comment]
By the way, I think we could really use a get_module_by_id function on RuntimeLinker (instead of doing self.list.read().iter().find(|m| m.id() == handle) 4 times), but I'm afraid it requires lifetime generics which make my brain hurt.

**Review by ultimaweapon — CHANGES_REQUESTED** [review]
I'm not a fan of subbing because it is likely to cause problems in the future.

**Comment by SuchAFuriousDeath** [comment]
I tend to agree, you can never be sure what's caused by what thing. I should have made this a draft, probably.

**Comment by SuchAFuriousDeath** [comment]
@ultimaweapon Also, what do I have to do to make this PR mergeable?

**Comment by ultimaweapon** [comment]
Better to keep only codes that have fully implementation. For partial implementation it should have a full implementation at least one branch and put `todo` macro on the other branches.

**Comment by SuchAFuriousDeath** [comment]
@ultimaweapon How will we implement /dev/console and stdout btw? Will we combine them into one stream?

**Comment by ultimaweapon** [comment]
My idea is we will combine them to stderr and add another tab on the GUI to show this.

**Comment by SuchAFuriousDeath** [comment]
What about when running just the kernel?

**Comment by ultimaweapon** [comment]
Same because right now the kernel print all its log to stdout. I'm keeping stderr specific for this.

**Comment by SuchAFuriousDeath** [comment]
I got too excited and put way to much in this PR once again.

**Comment by SuchAFuriousDeath** [comment]
The funny thing is, by implementing the devices and write instead of returning letting them fail, we actually hit a wall much earlier :(.

**Comment by ultimaweapon** [comment]
> I got too excited and put way to much in this PR once again.

Yeah you put too much things in a single PR. Better to close this and split it into multiple PR will be better.

**Pull request closed without merging**
