### PR TITLE
Adds Unicorn

### PR DESCRIPTION
**Pull request by ultimaweapon**
First step of #133.

### CODE REVIEW

**Review by bayedieng — APPROVED** [review]

**Review by bayedieng — CHANGES_REQUESTED** [review]
@ultimaweapon CI is likely failing due to pkg-config not being installed for macOS. Ubuntu ships with it so the Linux CI will likely not fail. Try installing pkg-config as a dependency on macOS CI. https://github.com/unicorn-engine/unicorn/blob/master/docs/COMPILE.md

**Comment by ultimaweapon** [comment]
But the error message is not related to`pkg-config`. If it is `pkg-config` it should say something like cannot find `pkg-config` program.

**Comment by bayedieng** [comment]
It Seems to rerun pkg-config multiple times? ```  
cargo:rerun-if-env-changed=UNICORN_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=UNICORN_STATIC
  cargo:rerun-if-env-changed=UNICORN_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR```

**Comment by ultimaweapon** [comment]
See #133 for more information why we are closing this.

**Pull request closed without merging**
