### PR TITLE
Implement syscall 649

### LINKED ISSUE #435: Unimplemented syscall 649
Reached after stubbing syscall 4. According to the PS4 dev wiki, this one is called 'sys_dynlib_get_obj_member'.

### PR DESCRIPTION
**Pull request by SuchAFuriousDeath**
Should close #435 (for now). I had this one in the drawer for a while, might as well make it official.
I'm not super certain about the unwrap_or(0).

### CODE REVIEW

**Comment by SuchAFuriousDeath** [comment]
@ultimaweapon By the way do you think we should make vscode run fmt on Ctrl+S? I think it can be done fairly easily.
https://stackoverflow.com/questions/67859926/how-to-run-cargo-fmt-on-save-in-vscode

**Comment by SuchAFuriousDeath** [comment]
Okay, this is wrong. It's not proc_param, it's module param :(. Close enough.

**Comment by SuchAFuriousDeath** [comment]
@ultimaweapon This is probably wrong, but close to being correct. Hopefully you can finish it off.

**Comment by ultimaweapon** [comment]
> @ultimaweapon By the way do you think we should make vscode run fmt on Ctrl+S? I think it can be done fairly easily.
> https://stackoverflow.com/questions/67859926/how-to-run-cargo-fmt-on-save-in-vscode

Good idea.

**Comment by SuchAFuriousDeath** [comment]
Actually, I think this is correct after all.

**Comment by SuchAFuriousDeath** [comment]
Just for clarity, though: I think this is logically correct, but I think this working depends on a correct implementation of Syscall 549. co we can't know for sure until that is done.

**Comment by ultimaweapon** [comment]
What are you looking for from 594?

**Comment by SuchAFuriousDeath** [comment]
I'm not actually sure. It just threw a segfault with my partial 594 implementation.

**Comment by SuchAFuriousDeath** [comment]
@ultimaweapon WIth your 594, this does reach tsc_freq. We still have a segfault after that for unknown reasons.

**Comment by ultimaweapon** [comment]
> @ultimaweapon WIth your 594, this does reach tsc_freq. (Which it didn't before) We still have a segfault after that for unknown reasons.

Let's do what we can do for now, as accurate as possible.

**Review by ultimaweapon — APPROVED** [review]

**Pull request merged**
