### PR TITLE
Add relocation constants

### PR DESCRIPTION
**Pull request by SuchAFuriousDeath**
Deduced from strings in the binary

### CODE REVIEW

**Comment by ultimaweapon** [comment]
Where did you get these from?

**Comment by SuchAFuriousDeath** [comment]
If you search for strings in ghidra and filter them with 'R_86', and then get where the resulting string are used (most of them), it's a function with a switch statement where the cases clearly correspond to relocation constants, some of which we are missing.

**Comment by ultimaweapon** [comment]
BTW do you want to join the organization?

**Comment by SuchAFuriousDeath** [comment]
You mean Obliteration? I'd love to.

**Comment by ultimaweapon** [comment]
Nope. I mean:

OrganizationXIII

BTW invitation has been sent. You can check organization page to see the invitation if you don't see in the notification.

**Review by ultimaweapon — APPROVED** [review]

**Pull request merged**
