### PR TITLE
Makes nullfs usable

### PR DESCRIPTION
**Pull request by SuchAFuriousDeath**

### CODE REVIEW

**Comment by ultimaweapon** [comment]
> I'm still not quite sure how to mount nullfs properly, since it has to be mounted on a vnode, but we don't currently have the games directory mounted. I guess we'll have to do another host mount?

My idea is to implement a fake PFS and use it to mount a game directory as a fake blue ray disc.

**Comment by SuchAFuriousDeath** [comment]
So... I should work on pfs next?

**Comment by ultimaweapon** [comment]
I think just make HostFS configurable so it can pretend to be any FS is better.

BTW I think we need more people so your PRs can be reviewed faster because I can take a look only on weekends. Some weekends I can't even do it because I have something to do. The problem is how to find more people?

**Comment by SuchAFuriousDeath** [comment]
I'm not sure. This one is pretty safe to merge I think.

**Comment by SuchAFuriousDeath** [comment]
By the way, the new guy making the PRs, mikusp, told me in Discord that his PRs aren't random, but that they implement things he himself encountered (He managed to somehow bypass what we're currently stuck on)

**Comment by SuchAFuriousDeath** [comment]
@ultimaweapon Here is his hacky WIP branch: https://github.com/mikusp/obliteration/commit/e5e4df13b839120c47933e761429961341cb7026. It's actually pretty insane how far he got. I suggest we let him into the org.

**Comment by SuchAFuriousDeath** [comment]
@ultimaweapon The ?Sized bound seems really weird here btw.
image
Either it should be on the trait itself(which applies it everywhere), or nowhere

**Review by VocalFan — APPROVED** [review]

**Comment by ultimaweapon** [comment]
@mikusp wanna join the @obhq organization? We need more developers so the PR can be reviewed properly.

**Comment by mikusp** [comment]
Yes of course!

**Comment by ultimaweapon** [comment]
Invitation has been sent.

**Pull request merged**
