### PR TITLE
Implements direct match for RegMgr::decode_key()

### LINKED ISSUE #335: Unimplemented regmgr_call with direct matched entry
```
++++++++++++++++++ P [00:00:00:00:071]:0x0000000000003498:kernel\src\regmgr\mod.rs:44
not yet implemented: regmgr_call with direct matched entry
```

### PR DESCRIPTION
**Pull request by ultimaweapon**
Fixes #335.

### CODE REVIEW

**Comment by VocalFan** [comment]
I think this is the most changelogs I've had to write in a single day haha

**Comment by ultimaweapon** [comment]
If we have more people it will be lot than this.

**Comment by ultimaweapon** [comment]
@gandalfthewhite19890404 can you test this?

**Comment by VocalFan** [comment]
> If we have more people it will be lot than this.

Ahaha, let's hope Hacktoberfest helps us when October begins.

**Comment by VocalFan** [comment]
> @gandalfthewhite19890404 can you test this?

Member of the Discord server (mattscreative) tested Sonic Mania.

```
not yet implemented: syscall 587 at 0x0000000000001c7a on /system/common/lib/libkernel.sprx
```

**Comment by gandalfthewhite19890404** [comment]
> @gandalfthewhite19890404 can you test this?

++++++++++++++++++ P [00:00:00:00:080]:0x00000000000001fc:kernel\src\regmgr\mod.rs:72
not yet implemented: decode regmgr_call request with v2 = 0

**Comment by ultimaweapon** [comment]
@gandalfthewhite19890404 Thanks. Do you mind tell what zone of your PS4 and the version of its firmware that you dump the firmware from? I suspect what cause the different result is because firmware zone VS game zone.

@VocalFan can you ask mattscreative for the same question?

**Comment by VocalFan** [comment]
Region: NA
Firmware: 5.05

**Comment by VocalFan** [comment]
Tell me if you have any questions for me or Matt, or if you find any discoveries haha.

**Comment by gandalfthewhite19890404** [comment]
> @gandalfthewhite19890404 Thanks. Do you mind tell what zone of your PS4 and the version of its firmware that you dump the firmware from? I suspect what cause the different result is because firmware zone VS game zone.
> 
> @VocalFan can you ask mattscreative for the same question?

7.55

**Review by bayedieng — APPROVED** [review]

**Pull request merged**
