### PR TITLE
Uses process credential on main thread

### PR DESCRIPTION
**Pull request by ultimaweapon**
This should be a correct one. I don't think the PS4 will allow the application main thread to use SceSysCore credential because it is a privileged one. We can find the correct answer without guessing in the function that do thread switching but the problem is I don't know where it is.

### CODE REVIEW

**Review by SuchAFuriousDeath — APPROVED** [review]

**Comment by ultimaweapon** [comment]
> Now we instantly fail on syscall 147 :(

The good news about this is it is a correct path for the games.

**Comment by SuchAFuriousDeath** [comment]
image

**Comment by ultimaweapon** [comment]
> image

Strange. Why you got int44. For me it is end up in sys_write.

**Comment by SuchAFuriousDeath** [comment]
And what happens after you implement it? Or rather, after you fake it and just return the len right away?

**Comment by SuchAFuriousDeath** [comment]
"Scepthread: Fatal error 'Can't set session id to 2 (errno = 1)'" is what it's trying to write for me btw

**Comment by SuchAFuriousDeath** [comment]
> > image
> 
> Strange. Why you got int44. For me it is end up in sys_write.

Sorry btw, I myself didn't realize that I had sys_write stubbed. I merged main into my WIP branch. By the way, we should be thinking about sys_mmap_dmem, that seems to be the main obstacle that's ahead of us. Mikusp said he already has some ideas.

**Comment by ultimaweapon** [comment]
I'll let you guys handle that. What I'm currently focus on is moving the application to run inside a VM.

**Comment by SuchAFuriousDeath** [comment]
Where do we even begin? 👀

**Comment by ultimaweapon** [comment]
Wait, you said @mikusp already have some ideas.

**Comment by SuchAFuriousDeath** [comment]
He has some ideas for dmem, but not for the privilege issue, that's what I was talking about.

**Comment by ultimaweapon** [comment]
> > image
> 
> Strange. Why you got int44. For me it is end up in sys_write.

You mean you got int44 after this?

**Comment by SuchAFuriousDeath** [comment]
yup

**Comment by SuchAFuriousDeath** [comment]
I guess I didn't actually say that 😅 Yeah, I get it right after. And from the description, it seems that it's the sys_setid. However, that means that is_system has to be true, doesn't it? 🤔

**Comment by ultimaweapon** [comment]
> However, that means that is_system has to be true, doesn't it?

It should not. I'm confused why it raise int44. It seems like the PS4 expect the process to be a system process somehow.

**Pull request merged**
