### PR TITLE
Implements symlook_obj

### PR DESCRIPTION
**Pull request by ultimaweapon**
Part of #300.

### CODE REVIEW

**Comment by VocalFan** [comment]
...Anything for me to do, Ultima? Today is a day off work for me.

**Comment by ultimaweapon** [comment]
Maybe find the name of `STT_UNK1`?

**Comment by VocalFan** [comment]
Saying that because I do well diving into the FreeBSD source code? ...Aight!

**Comment by ultimaweapon** [comment]
You can't find it in the FreeBSD because it is PS4 specific.

**Comment by VocalFan** [comment]
PS4 specific. Anything else ya want me to do?

*Values between 10-12 are usually OS/toolchain specific.*

**Comment by ultimaweapon** [comment]
Wanna find some the leaked official SDK? It probably have this value.

**Comment by VocalFan** [comment]
*Printing*

**Comment by VocalFan** [comment]
> Wanna find some the leaked official SDK? It probably have this value.

Want anything?

**Comment by ultimaweapon** [comment]
Nope. You can create a PR to update if you found it.

**Comment by VocalFan** [comment]
Found it!

```c
    case 0:
      result = "STT_NOTYPE";
      break;
    case 1:
      result = "Object";
      break;
    case 2:
      result = "Function";
      break;
    case 3:
      result = "Section";
      break;
    case 4:
      result = "Source File";
      break;
    case 5:
      result = "STT_COMMON";
      break;
    case 6:
      result = "STT_TLS";
      break;
    case 10:
      result = "STT_LOOS";
      break;
    case 11:
      result = "Module Entry";
      break;
    case 12:
      result = "STT_HIOS";
      break;
    default:
      result = "Unknown type";
      break;
```

**Comment by VocalFan** [comment]
From Orbis-Bin.c, line 58777 to 58809

**Comment by ultimaweapon** [comment]
No identifier (e.g. like `STT_TLS`)?

**Comment by VocalFan** [comment]
Nnnnope.

**Comment by VocalFan** [comment]
Check yo email, fool-

**Comment by ultimaweapon** [comment]
Thanks.

**Comment by VocalFan** [comment]
It'll probably help you a lot, haha.

**Comment by VocalFan** [comment]
I'll, uh, make a PR after this one.

**Comment by VocalFan** [comment]
Think that TLS_ENTRY would be a good name for it? As TLS types like STT_OBJECT and STT_FUNC are just called "Object" and "Function" in the code?

**Comment by ultimaweapon** [comment]
Did you mean `STT_ENTRY`?

**Comment by VocalFan** [comment]
...Yeah, was looking at another type... Which is why I typed TLS, but yes, STT_ENTRY

**Comment by VocalFan** [comment]
Also, gimme your opinion on that find I sent you on the email.

**Comment by ultimaweapon** [comment]
Can't download it yet due to there are some issue with my internet. From what I saw it looks very similar to what I got from a random guy on the internet.

**Comment by VocalFan** [comment]
> Can't download it yet due to there are some issue with my internet. From what I saw it looks very similar to what I got from a random guy on the internet.

*I also have the PS4 sdk... Like, proper exe.*

**Comment by VocalFan** [comment]
Check your email again.

**Pull request merged**
