### PR TITLE
Maps VM memory

### PR DESCRIPTION
**Pull request by ultimaweapon**
The reason we still use C++ with KVM is because https://crates.io/crates/kvm-ioctls is too high-level. We need something like raw KVM binding.

### CODE REVIEW

**Comment by SuchAFuriousDeath** [comment]
Found this: https://crates.io/crates/kvm-ioctls

**Comment by ultimaweapon** [comment]
> Found this: https://gitlab.com/preon/libkvm

Last commit was 5 years ago 😱

**Comment by SuchAFuriousDeath** [comment]
Maybe we could make our own binding crate

**Comment by SuchAFuriousDeath** [comment]
> > Found this: https://gitlab.com/preon/libkvm
> 
> Last commit was 5 years ago 😱

That's not necesarilly bad though, is it? Maybe there's just nothing to do because the api doesn't change.

**Comment by ultimaweapon** [comment]
> Maybe we could make our own binding crate

I don't think it wort the effort than using `cc` to build the C++ wrapper.

> > > Found this: https://gitlab.com/preon/libkvm
> > 
> > 
> > Last commit was 5 years ago 😱
> 
> That's not necesarilly bad though, is it? Maybe there's just nothing to do because the api doesn't change.

Just checking its code and it is also high-level the same as the first one.

**Review by SuchAFuriousDeath — APPROVED** [review]

**Pull request merged**
