### PR TITLE
Implements tlsinitsize for syscall 608

### PR DESCRIPTION
**Pull request by ultimaweapon**
Part of #265. This also move `VProc` and `VThread` to global scope for supports multi-threading app.

### CODE REVIEW

**Comment by bayedieng** [comment]
Wouldn't integrating our own tls be kindof beyond the scope of our project? Could using the rusttls crate provide the same results?

**Comment by ultimaweapon** [comment]
Our TLS implementation is a [Thread-local storage](https://en.wikipedia.org/wiki/Thread-local_storage), not [Transport Layer Security](https://en.wikipedia.org/wiki/Transport_Layer_Security) 😂.

**Comment by bayedieng** [comment]
Omg lol was so confused reading this PR initially I was wondering why I did not see crypto stuff.

**Comment by bayedieng** [comment]
Also, wanted to ask, how are you determining the validity of the syscall implementation? Is there a document you are referring to get ps4 syscalls if so which one?

**Review by bayedieng — APPROVED** [review]

**Comment by ultimaweapon** [comment]
@bayedieng by doing a reverse engineering on the PS4 kernel. The kernel can be dumped from a jailbroken PS4 but some information will be messed up, that why I created #273. Despite some information is messed up it is still very useful.

**Comment by ultimaweapon** [comment]
BTW you can find a dump from someone on the internet, although it is not a recent version but it is still very useful.

**Pull request merged**
