### PR TITLE
Removes jurplel/install-qt-action

### PR DESCRIPTION
**Pull request by ultimaweapon**
We got too many problems with it so better to remove it.

### CODE REVIEW

**Comment by VocalFan** [comment]
Thanks bestieeeeeeeeee

**Comment by VocalFan** [comment]
Also woah, flatpak builds!?

**Comment by ultimaweapon** [comment]
Because I can reuse the previous configurations without writing from scratch.

**Comment by VocalFan** [comment]
...This overall is fixing a LOT of pain we had with Actions... Removing god awful LLVM times for Windows, adding Flatpak builds, and getting rid of that broken Qt action.

**Comment by ultimaweapon** [comment]
Looks like LLVM installer for Windows does not provide `llvm-config.exe`.

**Comment by VocalFan** [comment]
@ultimaweapon Can't we cache the entirety of the LLVM build to speed up the process? After all, LLVM really only has to rebuild when there's a new version or conditions change. Which if they do, the build tool automatically replaces the old version.

Y'know... The lib/ folder?

**Comment by VocalFan** [comment]
image

**Comment by ultimaweapon** [comment]
Strange. Why the cache is not found.

**Comment by VocalFan** [comment]
81 minutes, rerunning to see cache time diff.

**Comment by VocalFan** [comment]
And down to 1 minute! But I think that can be even quicker... Maybe. @ultimaweapon Do you still need to do the Download LLVM step on "LLVM for Windows" even though  you already have the compiled lib? If not, that'd make it basically be instant.

**Comment by ultimaweapon** [comment]
That one is required to generate a key.

**Comment by VocalFan** [comment]
Ah, I see that now. Either way Ultima, I'd say that was a damn good suggestion haha. And over all, good work! Got any other changes?

**Review by VocalFan — APPROVED** [review]

**Comment by ultimaweapon** [comment]
Just got another idea. Instead of hashing the downloaded file we can hash the URL instead. But that will take another hour so let's use the current version for now and implement this together with LLVM upgrade.

**Pull request merged**
