### PR TITLE
Uses different stack when executing PS4 app

### PR DESCRIPTION
**Pull request by ultimaweapon**
One of a solution of #295.

### CODE REVIEW

**Comment by ultimaweapon** [comment]
@VocalFan can you test this to see if everything is still working as expected?

**Comment by VocalFan** [comment]
The Division, PDX and Amplitude reach Syscall 599 relocation type 6 (normal)

**Comment by VocalFan** [comment]
IDK if this is normal or not as Syscall 608 is WIP, but any game trying to use 608 crashes the Kernel

**Comment by ultimaweapon** [comment]
Does it crash in the same way as before? Or this time a different one?

**Comment by VocalFan** [comment]
> Does it crash in the same way as before? Or this time a different one?

Uh, I mean it doesn't give the 'Invalid Argument' prompt, just immediately 'The Kernel Crashed'

**Comment by VocalFan** [comment]
<details>
  <summary>
    Persona 5 Royal on latest dev build:
  </summary>
  <code>++++++++++++++++++ I [00:00:00:00:000]:0x0000000000028804:kernel\src/main.rs:84
Starting Obliteration Kernel.
System directory    : G:\obSTORAGE\dev_sys
Game directory      : G:\obSTORAGE\dev_hdd0\CUSA17416
Debug dump directory: C:\Users\Windows Games\AppData\Local\OBHQ\Obliteration\kernel
++++++++++++++++++ I [00:00:00:00:000]:0x0000000000028804:kernel\src/main.rs:97
Initializing arc4random.
++++++++++++++++++ I [00:00:00:00:000]:0x0000000000028804:kernel\src/main.rs:101
Initializing LLVM.
++++++++++++++++++ I [00:00:00:00:000]:0x0000000000028804:kernel\src/main.rs:107
Initializing file system.
++++++++++++++++++ I [00:00:00:00:001]:0x0000000000028804:kernel\src/main.rs:118
Initializing memory manager.
++++++++++++++++++ I [00:00:00:00:001]:0x0000000000028804:kernel\src/main.rs:121
Page size is             : 4096
Allocation granularity is: 65536
++++++++++++++++++ I [00:00:00:00:001]:0x0000000000028804:kernel\src/main.rs:134
Initializing virtual process.
++++++++++++++++++ I [00:00:00:00:001]:0x0000000000028804:kernel\src/main.rs:142
Initializing runtime linker.
++++++++++++++++++ I [00:00:00:00:026]:0x0000000000028804:kernel\src/main.rs:153
Application   : /mnt/sandbox/CUSA17416_000/app0/eboot.bin
Image format  : SELF
Image type    : ET_SCE_DYNEXEC
Program 0     : 0x0000000000004000:0x0000000001a25f14 => 0x0000000000000000:0x0000000001a21f14 PT_LOAD
Program 1     : 0x0000000001a28000:0x0000000001a80ec8 => 0x0000000001c00000:0x0000000001c58ec8 PT_SCE_RELRO
Program 2     : 0x0000000001a84000:0x0000000001f46a68 => 0x0000000001e00000:0x00000000025995d0 PT_LOAD
Program 3     : 0x0000000001a84000:0x0000000001a84058 => 0x0000000001e00000:0x0000000001e00058 PT_SCE_PROCPARAM
Program 4     : 0x000000000203ff18:0x0000000002040c78 => 0x0000000000000000:0x0000000000000d60 PT_DYNAMIC
Program 5     : 0x0000000000004000:0x0000000000004015 => 0x0000000000000000:0x0000000000000015 PT_INTERP
Program 6     : 0x0000000000000000:0x0000000000000000 => 0x0000000000000000:0x0000000000000000 PT_TLS
Program 7     : 0x00000000019f07b8:0x0000000001a25f14 => 0x00000000019ec7b8:0x0000000001a21f14 PT_GNU_EH_FRAME
Program 8     : 0x0000000001f46a70:0x0000000002040c78 => 0x0000000000000000:0x0000000000000000 PT_SCE_DYNLIBDATA
Program 9     : 0x0000000002040c80:0x0000000002040ccc => 0x0000000000000000:0x0000000000000000 PT_SCE_COMMENT
Program 10    : 0x0000000002040ccc:0x0000000002041589 => 0x0000000000000000:0x0000000000000000 PT_SCE_VERSION
Needed        : libSceSysmodule.prx
Needed        : libSceUserService.prx
Needed        : libSceSystemService.prx
Needed        : libSceFiber.prx
Needed        : libSceFios2.prx
Needed        : libScePad.prx
Needed        : libSceVideoOut.prx
Needed        : libSceGnmDriver.prx
Needed        : libkernel.prx
Needed        : libSceMouse.prx
Needed        : libSceIme.prx
Needed        : libSceRtc.prx
Needed        : libSceFont-module.prx
Needed        : libSceFontFt-module.prx
Needed        : libSceAudioOut.prx
Needed        : libSceSaveData.prx
Needed        : libSceSaveDataDialog.prx
Needed        : libSceCommonDialog.prx
Needed        : libSceScreenShot.prx
Needed        : libSceGameLiveStreaming.prx
Needed        : libSceVideoRecording.prx
Needed        : libSceNet.prx
Needed        : libSceNetCtl.prx
Needed        : libSceNpCommon.prx
Needed        : libSceNpManager.prx
Needed        : libSceNpScoreRanking.prx
Needed        : libSceNpTrophy.prx
Needed        : libSceNpTus.prx
Needed        : libSceNpMatching2.prx
Needed        : libSceSsl2.prx
Needed        : libSceHttp.prx
Needed        : libSceNpWebApi.prx
Needed        : libSceAppContent.prx
Needed        : libSceImeBackend.prx
Needed        : libSceErrorDialog.prx
Needed        : libSceVideodec2.prx
Needed        : libSceSharePlay.prx
Needed        : libScePlayGo.prx
Needed        : libSceJson2.prx
Needed        : libSceSigninDialog.prx
Needed        : libSceMsgDialog.prx
Needed        : libScePlayGoDialog.prx
Needed        : libSceAt9Enc.prx
Needed        : libSceAjm.prx
Needed        : libc.prx
Module flags  : MAIN_PROG | TEXT_REL | UNK2
TLS index     : 1
Memory address: 0x00000234c9ce0000:0x00000234cc87c000
Initialization: 0x00000234ca0e0020
Entry address : 0x00000234ca0e0080
Finalization  : 0x00000234cb7c3320
TLS init      : 0x00000234ca0e0000:0x00000234ca0e0000
TLS size      : 0
EH header     : 0x00000234cbacc7b8:0x00000234cbb01f14
EH frame      : 0x00000234cb9e3bc4:0x00000234cbacc7b8
Process param : 0x00000234cbee0000:0x00000234cbee0058
Program 0 is mapped to 0x00000234ca0e0000:0x00000234cbb04000 with EXECUTE | READ.
Program 1 is mapped to 0x00000234cbce0000:0x00000234cbd3c000 with READ.
Program 2 is mapped to 0x00000234cbee0000:0x00000234cc67c000 with WRITE | READ.
++++++++++++++++++ I [00:00:00:00:026]:0x0000000000028804:kernel\src/main.rs:161
Loading /system/common/lib/libkernel.sprx.
++++++++++++++++++ I [00:00:00:00:027]:0x0000000000028804:kernel\src/main.rs:172
Image format  : ELF
Image type    : ET_SCE_DYNAMIC
Program 0     : 0x0000000000004000:0x0000000000054318 => 0x0000000000000000:0x0000000000050318 PT_LOAD
Program 1     : 0x0000000000058000:0x0000000000059010 => 0x0000000000054000:0x0000000000055010 PT_SCE_RELRO
Program 2     : 0x000000000005c000:0x000000000005c330 => 0x0000000000058000:0x000000000008f590 PT_LOAD
Program 3     : 0x000000000005c000:0x000000000005c020 => 0x0000000000058000:0x0000000000058020 PT_SCE_MODULE_PARAM
Program 4     : 0x000000000006d488:0x000000000006d9a8 => 0x0000000000000000:0x0000000000000520 PT_DYNAMIC
Program 5     : 0x0000000000000000:0x0000000000000000 => 0x0000000000000000:0x0000000000000000 PT_TLS
Program 6     : 0x0000000000050e9c:0x0000000000054318 => 0x000000000004ce9c:0x0000000000050318 PT_GNU_EH_FRAME
Program 7     : 0x000000000005c330:0x000000000006d9a8 => 0x0000000000000000:0x0000000000000000 PT_SCE_DYNLIBDATA
Program 8     : 0x0000000000000000:0x0000000000000000 => 0x0000000000000000:0x0000000000000000 PT_SCE_VERSION
Needed        : libSceLibcInternal.prx
Needed        : libSceGnmDriver.prx
Module flags  : UNK1
TLS index     : 0
Memory address: 0x00000234cc880000:0x00000234ccb10000
Entry address : 0x00000234cc8a87e8
Finalization  : 0x00000234cc8b67a0
TLS init      : 0x00000234cc880000:0x00000234cc880000
TLS size      : 0
EH header     : 0x00000234cc8cce9c:0x00000234cc8d0318
EH frame      : 0x00000234cc8bc270:0x00000234cc8cce9c
Program 0 is mapped to 0x00000234cc880000:0x00000234cc8d4000 with EXECUTE | READ.
Program 1 is mapped to 0x00000234cc8d4000:0x00000234cc8d8000 with READ.
Program 2 is mapped to 0x00000234cc8d8000:0x00000234cc910000 with WRITE | READ.
++++++++++++++++++ I [00:00:00:00:027]:0x0000000000028804:kernel\src/main.rs:183
Loading /system/common/lib/libSceLibcInternal.sprx.
++++++++++++++++++ I [00:00:00:00:028]:0x0000000000028804:kernel\src/main.rs:194
Image format  : ELF
Image type    : ET_SCE_DYNAMIC
Program 0     : 0x0000000000004000:0x0000000000129c8c => 0x0000000000000000:0x0000000000125c8c PT_LOAD
Program 1     : 0x000000000012c000:0x0000000000130510 => 0x0000000000128000:0x000000000012c510 PT_SCE_RELRO
Program 2     : 0x0000000000134000:0x000000000013dbe8 => 0x0000000000130000:0x0000000000149110 PT_LOAD
Program 3     : 0x0000000000134000:0x000000000013a4d8 => 0x0000000000130000:0x00000000001364d8 PT_SCE_MODULE_PARAM
Program 4     : 0x000000000016cc78:0x000000000016cf18 => 0x0000000000000000:0x00000000000002a0 PT_DYNAMIC
Program 5     : 0x000000000013a4e0:0x000000000013a660 => 0x00000000001364e0:0x0000000000136a40 PT_TLS
Program 6     : 0x0000000000122a88:0x0000000000129c8c => 0x000000000011ea88:0x0000000000125c8c PT_GNU_EH_FRAME
Program 7     : 0x000000000013dc00:0x000000000016cf18 => 0x0000000000000000:0x0000000000000000 PT_SCE_DYNLIBDATA
Program 8     : 0x0000000000000000:0x0000000000000000 => 0x0000000000000000:0x0000000000000000 PT_SCE_VERSION
Needed        : libkernel.prx
Needed        : libSceLibcInternal.prx
Module flags  : UNK1
TLS index     : 2
Memory address: 0x00000234ccb10000:0x00000234cce5c000
Finalization  : 0x00000234ccbe53b0
TLS init      : 0x00000234ccc464e0:0x00000234ccc46660
TLS size      : 1376
EH header     : 0x00000234ccc2ea88:0x00000234ccc35c8c
EH frame      : 0x00000234ccc09664:0x00000234ccc2ea88
Program 0 is mapped to 0x00000234ccb10000:0x00000234ccc38000 with EXECUTE | READ.
Program 1 is mapped to 0x00000234ccc38000:0x00000234ccc40000 with READ.
Program 2 is mapped to 0x00000234ccc40000:0x00000234ccc5c000 with WRITE | READ.
++++++++++++++++++ I [00:00:00:00:028]:0x0000000000028804:kernel\src/main.rs:197
Initializing system call routines.
++++++++++++++++++ I [00:00:00:00:028]:0x0000000000028804:kernel\src/main.rs:203
Initializing execution engine.
++++++++++++++++++ I [00:00:00:00:028]:0x0000000000028804:kernel\src/main.rs:218
Patching modules.
++++++++++++++++++ I [00:00:00:00:085]:0x0000000000028804:kernel\src/main.rs:222
353 patch(es) have been applied to /system/common/lib/libkernel.sprx.
187 patch(es) have been applied to /system/common/lib/libSceLibcInternal.sprx.
2 module(s) have been patched successfully.
++++++++++++++++++ I [00:00:00:00:085]:0x0000000000028804:kernel\src/main.rs:272
Starting application.
++++++++++++++++++ W [00:00:00:00:087]:0x0000000000028804:kernel\src\syscalls\mod.rs:68
Syscall 608 failed: invalid argument.
++++++++++++++++++ P [00:00:00:00:087]:0x0000000000028804:kernel\src\syscalls\mod.rs:83
not yet implemented: int 0x44 at at 0x000000000002b13a on /system/common/lib/libkernel.sprx
</code>
</details>

<details>
  <summary>
    Persona 5 Royal on this PR build:
  </summary>
  <code>++++++++++++++++++ I [00:00:00:00:000]:0x0000000000023c08:kernel\src/main.rs:85
Starting Obliteration Kernel.
System directory    : G:\obSTORAGE\dev_sys
Game directory      : G:\obSTORAGE\dev_hdd0\CUSA17416
Debug dump directory: C:\Users\Windows Games\AppData\Local\OBHQ\Obliteration\kernel
++++++++++++++++++ I [00:00:00:00:000]:0x0000000000023c08:kernel\src/main.rs:98
Initializing arc4random.
++++++++++++++++++ I [00:00:00:00:000]:0x0000000000023c08:kernel\src/main.rs:102
Initializing LLVM.
++++++++++++++++++ I [00:00:00:00:000]:0x0000000000023c08:kernel\src/main.rs:108
Initializing file system.
++++++++++++++++++ I [00:00:00:00:001]:0x0000000000023c08:kernel\src/main.rs:119
Initializing memory manager.
++++++++++++++++++ I [00:00:00:00:001]:0x0000000000023c08:kernel\src/main.rs:122
Page size is             : 4096
Allocation granularity is: 65536
++++++++++++++++++ I [00:00:00:00:001]:0x0000000000023c08:kernel\src/main.rs:135
Initializing virtual process.
++++++++++++++++++ I [00:00:00:00:001]:0x0000000000023c08:kernel\src/main.rs:143
Initializing runtime linker.
++++++++++++++++++ I [00:00:00:00:017]:0x0000000000023c08:kernel\src/main.rs:154
Application   : /mnt/sandbox/CUSA17416_000/app0/eboot.bin
Image format  : SELF
Image type    : ET_SCE_DYNEXEC
Program 0     : 0x0000000000004000:0x0000000001a25f14 => 0x0000000000000000:0x0000000001a21f14 PT_LOAD
Program 1     : 0x0000000001a28000:0x0000000001a80ec8 => 0x0000000001c00000:0x0000000001c58ec8 PT_SCE_RELRO
Program 2     : 0x0000000001a84000:0x0000000001f46a68 => 0x0000000001e00000:0x00000000025995d0 PT_LOAD
Program 3     : 0x0000000001a84000:0x0000000001a84058 => 0x0000000001e00000:0x0000000001e00058 PT_SCE_PROCPARAM
Program 4     : 0x000000000203ff18:0x0000000002040c78 => 0x0000000000000000:0x0000000000000d60 PT_DYNAMIC
Program 5     : 0x0000000000004000:0x0000000000004015 => 0x0000000000000000:0x0000000000000015 PT_INTERP
Program 6     : 0x0000000000000000:0x0000000000000000 => 0x0000000000000000:0x0000000000000000 PT_TLS
Program 7     : 0x00000000019f07b8:0x0000000001a25f14 => 0x00000000019ec7b8:0x0000000001a21f14 PT_GNU_EH_FRAME
Program 8     : 0x0000000001f46a70:0x0000000002040c78 => 0x0000000000000000:0x0000000000000000 PT_SCE_DYNLIBDATA
Program 9     : 0x0000000002040c80:0x0000000002040ccc => 0x0000000000000000:0x0000000000000000 PT_SCE_COMMENT
Program 10    : 0x0000000002040ccc:0x0000000002041589 => 0x0000000000000000:0x0000000000000000 PT_SCE_VERSION
Needed        : libSceSysmodule.prx
Needed        : libSceUserService.prx
Needed        : libSceSystemService.prx
Needed        : libSceFiber.prx
Needed        : libSceFios2.prx
Needed        : libScePad.prx
Needed        : libSceVideoOut.prx
Needed        : libSceGnmDriver.prx
Needed        : libkernel.prx
Needed        : libSceMouse.prx
Needed        : libSceIme.prx
Needed        : libSceRtc.prx
Needed        : libSceFont-module.prx
Needed        : libSceFontFt-module.prx
Needed        : libSceAudioOut.prx
Needed        : libSceSaveData.prx
Needed        : libSceSaveDataDialog.prx
Needed        : libSceCommonDialog.prx
Needed        : libSceScreenShot.prx
Needed        : libSceGameLiveStreaming.prx
Needed        : libSceVideoRecording.prx
Needed        : libSceNet.prx
Needed        : libSceNetCtl.prx
Needed        : libSceNpCommon.prx
Needed        : libSceNpManager.prx
Needed        : libSceNpScoreRanking.prx
Needed        : libSceNpTrophy.prx
Needed        : libSceNpTus.prx
Needed        : libSceNpMatching2.prx
Needed        : libSceSsl2.prx
Needed        : libSceHttp.prx
Needed        : libSceNpWebApi.prx
Needed        : libSceAppContent.prx
Needed        : libSceImeBackend.prx
Needed        : libSceErrorDialog.prx
Needed        : libSceVideodec2.prx
Needed        : libSceSharePlay.prx
Needed        : libScePlayGo.prx
Needed        : libSceJson2.prx
Needed        : libSceSigninDialog.prx
Needed        : libSceMsgDialog.prx
Needed        : libScePlayGoDialog.prx
Needed        : libSceAt9Enc.prx
Needed        : libSceAjm.prx
Needed        : libc.prx
Module flags  : MAIN_PROG | TEXT_REL | UNK2
TLS index     : 1
Memory address: 0x000001cee3480000:0x000001cee601c000
Initialization: 0x000001cee3880020
Entry address : 0x000001cee3880080
Finalization  : 0x000001cee4f63320
TLS init      : 0x000001cee3880000:0x000001cee3880000
TLS size      : 0
EH header     : 0x000001cee526c7b8:0x000001cee52a1f14
EH frame      : 0x000001cee5183bc4:0x000001cee526c7b8
Process param : 0x000001cee5680000:0x000001cee5680058
Program 0 is mapped to 0x000001cee3880000:0x000001cee52a4000 with EXECUTE | READ.
Program 1 is mapped to 0x000001cee5480000:0x000001cee54dc000 with READ.
Program 2 is mapped to 0x000001cee5680000:0x000001cee5e1c000 with WRITE | READ.
++++++++++++++++++ I [00:00:00:00:018]:0x0000000000023c08:kernel\src/main.rs:162
Loading /system/common/lib/libkernel.sprx.
++++++++++++++++++ I [00:00:00:00:018]:0x0000000000023c08:kernel\src/main.rs:173
Image format  : ELF
Image type    : ET_SCE_DYNAMIC
Program 0     : 0x0000000000004000:0x0000000000054318 => 0x0000000000000000:0x0000000000050318 PT_LOAD
Program 1     : 0x0000000000058000:0x0000000000059010 => 0x0000000000054000:0x0000000000055010 PT_SCE_RELRO
Program 2     : 0x000000000005c000:0x000000000005c330 => 0x0000000000058000:0x000000000008f590 PT_LOAD
Program 3     : 0x000000000005c000:0x000000000005c020 => 0x0000000000058000:0x0000000000058020 PT_SCE_MODULE_PARAM
Program 4     : 0x000000000006d488:0x000000000006d9a8 => 0x0000000000000000:0x0000000000000520 PT_DYNAMIC
Program 5     : 0x0000000000000000:0x0000000000000000 => 0x0000000000000000:0x0000000000000000 PT_TLS
Program 6     : 0x0000000000050e9c:0x0000000000054318 => 0x000000000004ce9c:0x0000000000050318 PT_GNU_EH_FRAME
Program 7     : 0x000000000005c330:0x000000000006d9a8 => 0x0000000000000000:0x0000000000000000 PT_SCE_DYNLIBDATA
Program 8     : 0x0000000000000000:0x0000000000000000 => 0x0000000000000000:0x0000000000000000 PT_SCE_VERSION
Needed        : libSceLibcInternal.prx
Needed        : libSceGnmDriver.prx
Module flags  : UNK1
TLS index     : 0
Memory address: 0x000001cee6020000:0x000001cee62b0000
Entry address : 0x000001cee60487e8
Finalization  : 0x000001cee60567a0
TLS init      : 0x000001cee6020000:0x000001cee6020000
TLS size      : 0
EH header     : 0x000001cee606ce9c:0x000001cee6070318
EH frame      : 0x000001cee605c270:0x000001cee606ce9c
Program 0 is mapped to 0x000001cee6020000:0x000001cee6074000 with EXECUTE | READ.
Program 1 is mapped to 0x000001cee6074000:0x000001cee6078000 with READ.
Program 2 is mapped to 0x000001cee6078000:0x000001cee60b0000 with WRITE | READ.
++++++++++++++++++ I [00:00:00:00:018]:0x0000000000023c08:kernel\src/main.rs:184
Loading /system/common/lib/libSceLibcInternal.sprx.
++++++++++++++++++ I [00:00:00:00:019]:0x0000000000023c08:kernel\src/main.rs:195
Image format  : ELF
Image type    : ET_SCE_DYNAMIC
Program 0     : 0x0000000000004000:0x0000000000129c8c => 0x0000000000000000:0x0000000000125c8c PT_LOAD
Program 1     : 0x000000000012c000:0x0000000000130510 => 0x0000000000128000:0x000000000012c510 PT_SCE_RELRO
Program 2     : 0x0000000000134000:0x000000000013dbe8 => 0x0000000000130000:0x0000000000149110 PT_LOAD
Program 3     : 0x0000000000134000:0x000000000013a4d8 => 0x0000000000130000:0x00000000001364d8 PT_SCE_MODULE_PARAM
Program 4     : 0x000000000016cc78:0x000000000016cf18 => 0x0000000000000000:0x00000000000002a0 PT_DYNAMIC
Program 5     : 0x000000000013a4e0:0x000000000013a660 => 0x00000000001364e0:0x0000000000136a40 PT_TLS
Program 6     : 0x0000000000122a88:0x0000000000129c8c => 0x000000000011ea88:0x0000000000125c8c PT_GNU_EH_FRAME
Program 7     : 0x000000000013dc00:0x000000000016cf18 => 0x0000000000000000:0x0000000000000000 PT_SCE_DYNLIBDATA
Program 8     : 0x0000000000000000:0x0000000000000000 => 0x0000000000000000:0x0000000000000000 PT_SCE_VERSION
Needed        : libkernel.prx
Needed        : libSceLibcInternal.prx
Module flags  : UNK1
TLS index     : 2
Memory address: 0x000001cee62b0000:0x000001cee65fc000
Finalization  : 0x000001cee63853b0
TLS init      : 0x000001cee63e64e0:0x000001cee63e6660
TLS size      : 1376
EH header     : 0x000001cee63cea88:0x000001cee63d5c8c
EH frame      : 0x000001cee63a9664:0x000001cee63cea88
Program 0 is mapped to 0x000001cee62b0000:0x000001cee63d8000 with EXECUTE | READ.
Program 1 is mapped to 0x000001cee63d8000:0x000001cee63e0000 with READ.
Program 2 is mapped to 0x000001cee63e0000:0x000001cee63fc000 with WRITE | READ.
++++++++++++++++++ I [00:00:00:00:019]:0x0000000000023c08:kernel\src/main.rs:198
Initializing system call routines.
++++++++++++++++++ I [00:00:00:00:019]:0x0000000000023c08:kernel\src/main.rs:204
Initializing execution engine.
++++++++++++++++++ I [00:00:00:00:019]:0x0000000000023c08:kernel\src/main.rs:225
Patching modules.
++++++++++++++++++ I [00:00:00:00:076]:0x0000000000023c08:kernel\src/main.rs:229
353 patch(es) have been applied to /system/common/lib/libkernel.sprx.
187 patch(es) have been applied to /system/common/lib/libSceLibcInternal.sprx.
2 module(s) have been patched successfully.
++++++++++++++++++ I [00:00:00:00:076]:0x0000000000023c08:kernel\src/main.rs:281
Allocating application stack.
++++++++++++++++++ I [00:00:00:00:076]:0x0000000000023c08:kernel\src/main.rs:299
Starting application.
</code>

</details>

This is like the fanciest Markdown comment I've ever made on Github lol

**Comment by VocalFan** [comment]
`Stop reason: Exception 0xc0000005 encountered at address 0x27af27e99b6: Unknown access violation (code 3) at location 0x00000000` - Kernel

**Comment by ultimaweapon** [comment]
Okay thanks for testing.

**Comment by ultimaweapon** [comment]
#299 is working and it is better than this one so I will close this.

**Pull request closed without merging**
