### PR TITLE
Add name sorting.

### PR DESCRIPTION
**Pull request by VocalFan**
Fixed an issue to make sure the Widget refreshes after sorting, also fixed an issue with icons not being uniformly sized. Here's an example of the sorting:

Before:
image

After:
image

### CODE REVIEW

**Review by ultimaweapon — CHANGES_REQUESTED** [review]
This is not a correct way to do it. Better to understand how Model/View in Qt is working before implement this.

**Comment by ultimaweapon** [comment]
Wait, why this contains the commits that already merged?

**Comment by VocalFan** [comment]
> Wait, why this contains the commits that already merged?

Probs because it's the same branch just... Updated?

**Comment by ultimaweapon** [comment]
Should not be a problem if GitHub does not show any conflicts here.

**Comment by VocalFan** [comment]
I think we should uh, fix that issue if an app has an abnormally large icon.

**Comment by ultimaweapon** [comment]
What do you mean by a large icon?

**Comment by VocalFan** [comment]
Look at the before and after. Since Itemzflow has a 1000px logo, it was way larger than the other logos that were 512px. Since the PS4 ui just downscales the icon to match the normal size, I did so as well.

**Comment by VocalFan** [comment]
Don't merge btw, gotta fix an issue that capital letters are prioritized. In unicode and ascii, capital letters come before lower letters in order.

**Review by ultimaweapon — APPROVED** [review]

**Pull request merged**
