### PR TITLE
Implements mkdir for Windows

### LINKED ISSUE #755: Add raw_mkdir for Windows.
After we completed #746 , we still need to complete raw_mkdir to continue. There's currently only a linux implementation.

### PR DESCRIPTION
**Pull request by ultimaweapon**
Closes #755.

### CODE REVIEW

**Review by SuchAFuriousDeath — DISMISSED** [review]

**Comment by ultimaweapon** [comment]
@VocalFan can you test this?

**Comment by VocalFan** [comment]
Ah, you reached the same point I did, sadly.

@ultimaweapon 
```
++++++++++++++++++ E [00:00:00:00:250]:0x0000000000004eb0: kernel\src/main.rs:670
Error while running kernel: filesystem initialization failed -> cannot lookup /dev -> couldn't open the specified file -> Access is denied. (os error 5).
```
It's mainly due to the folder already existing.

If I delete the empty dev folder, it creates the folder and continues to mnt... Which since mnt already exists:
```
++++++++++++++++++ E [00:00:00:00:211]:0x0000000000004f90: kernel\src/main.rs:670
Error while running kernel: couldn't mount /mnt -> fspath is not found -> cannot lookup 'mnt' from component #0 -> couldn't open the specified file -> Access is denied. (os error 5).
```

**Comment by ultimaweapon** [comment]
This is bad. Why Windows report access is denied instead of something like file already exists.

**Comment by ultimaweapon** [comment]
I think I found a solution now.

**Comment by VocalFan** [comment]
> I think I found a solution now.

...Got 8 minutes then I gotta go :P

**Comment by VocalFan** [comment]
@ultimaweapon Before I test this when I go home... I basically had an identical implementation, however, the error code number for when I got access denied was (-1073741790)... Don't know if that helps

**Comment by VocalFan** [comment]
```
++++++++++++++++++ E [00:00:00:00:366]:0x0000000000003124: kernel\src/main.rs:670
Error while running kernel: filesystem initialization failed -> cannot lookup /dev -> couldn't open the specified file -> Access is denied. (os error 5).
```

**Comment by VocalFan** [comment]
```
>Err_6.4.5.exe -1073741771
# for decimal -1073741771 / hex 0xc0000035

  STATUS_OBJECT_NAME_COLLISION                                   ntstatus.h
# Object Name already exists.
# as an HRESULT: Severity: FAILURE (1), FACILITY_NULL (0x0), Code 0x35
```

**Comment by VocalFan** [comment]
Okay, so I confirmed that STATUS_OBJECT_NAME_COLLISION is the actual error code, but... That doesn't work with your ERROR_FILE_EXISTS unwrapping, it just errors anyways with access denied.

**Comment by ultimaweapon** [comment]
Wait, the previous version already correct. The error you got came from another issue so I will revert my last commit.

**Review by SuchAFuriousDeath — APPROVED** [review]

**Pull request merged**
