### PR TITLE
Implements syscall 165

### LINKED ISSUE #397: Unimplemented Syscall 165
I was able to get my Syscall Called: # to work on the rewrite, however, I can't figure out how to perform my "skip syscall and see what else needs implemented" code.

Anyways, rewrite now brings us this:

Syscall 165, also known as [sysarch](https://man.freebsd.org/cgi/man.cgi?query=sysarch&apropos=0&sektion=2&manpath=FreeBSD+9.1-RELEASE&arch=amd64&format=html)

The source code is here: https://cgit.freebsd.org/src/tree/sys/amd64/amd64/sys_machdep.c?h=releng/9.1#n91

Note, Sysarch syscall changes depending on architecture, this is going off of the PS4 using a 64-bit CPU (AMD64 arch)

### PR DESCRIPTION
**Pull request by ultimaweapon**
Fixes #397.

### CODE REVIEW

**Comment by VocalFan** [comment]
Some errors on certain games, will post in Issues.

**Comment by VocalFan** [comment]
#400 #401 #402

**Comment by bayedieng** [comment]
> #400 #401 #402

Waiting for these to be fixed to merge. Also, was looking into finally starting the lifter but it seems changes are still being made to it as of the last two PRs. Will go ahead and begin once this is merged.

**Comment by ultimaweapon** [comment]
Those issues should not cause any major changes to the EE. So the current changes in this PR should be stable enough for you to continue working on the EE.

**Comment by ultimaweapon** [comment]
Not sure if you are waiting for those issues to be fixed. If yes we should fix it on a separated PR because it might be required some work.

**Comment by bayedieng** [comment]
> Not sure if you are waiting for those issues to be fixed. If yes we should fix it on a separated PR because it might be required some work.

yeah I was, will merge this then.

**Review by bayedieng — APPROVED** [review]

**Pull request merged**
