### PR TITLE
Implements eh_frame, eh_frame_hdr_size and eh_frame_size for syscall 608

### PR DESCRIPTION
**Pull request by ultimaweapon**
Part of #265.

### CODE REVIEW

**Comment by VocalFan** [comment]
"Will Syscall 608 ever finish being implemented? Find out on the next pull request of Obliteration Z!"

**Comment by VocalFan** [comment]
Glad you got the humor, Ultima~!

**Comment by VocalFan** [comment]
And don't act like I don't notice that Panic hook :P
...*Finally-*

**Comment by ultimaweapon** [comment]
Sorry I don't understand what you said.

**Comment by VocalFan** [comment]
> Sorry I don't understand what you said.

I'm saying to run `cargo clippy --fix --allow-dirty`

Because Clippy seems to have some fixes sometimes... Especially when you edit the logging system.

**Comment by ultimaweapon** [comment]
> And don't act like I don't notice that Panic hook :P

I mean this one.

**Comment by VocalFan** [comment]
Ah, just proud we finally have a Panic hook again, seeing as Simplelog well, kinda died lol. We just continued off our own logging system which means we never got that panic hook.

**Review by bayedieng — APPROVED** [review]

**Pull request merged**
