### PR TITLE
Implements syscall 610

### LINKED ISSUE #321: Unimplemented Syscall 610
```
++++++++++++++++++ P [00:00:00:01:412]:0x0000000000004254:kernel\src\syscalls\mod.rs:66
not yet implemented: syscall 610 at 0x0000000000001eda on /system/common/lib/libkernel.sprx
```
CUSTOM PS4 SYSCALL
<html>
<body>

Syscall ID | PS4 FW Version | Syscall name | Syscall usermode prototype
-- | -- | -- | --
610 | <=1.01? | sys_budget_get_ptype | int sys_budget_get_ptype(int budgetID)

</body>
</html>

### PR DESCRIPTION
**Pull request by ultimaweapon**
Fixes #321.

### CODE REVIEW

**Comment by VocalFan** [comment]
Will test after work

**Comment by gandalfthewhite19890404** [comment]
```
Starting application.
++++++++++++++++++ W [00:00:00:00:031]:0x00000000000036a8:kernel\src\syscalls\mod.rs:74
Syscall 610 failed: no such file or directory.
++++++++++++++++++ P [00:00:00:00:031]:0x00000000000036a8:kernel\src\syscalls\mod.rs:67
not yet implemented: syscall 532 at 0x00000000000017fa on /system/common/lib/libkernel.sprx
```

What file it needs?

**Comment by VocalFan** [comment]
Work made me pass TF out when I got home. Either way, all games now go to Syscall 532.

**Comment by VocalFan** [comment]
@ultimaweapon Also you told me you didn't like stubbing but... What you've been doing IS stubbing! Putting placeholders so code can be worked on later! Like how for the syscall that fetched Resource Limits, you had Windows have placeholder values of uside::max! Or for this, have it direct to an error code that somehow lets the program continue running!

**Comment by ultimaweapon** [comment]
It is not stubbing. It is one on the branch that can be using.

**Review by bayedieng — APPROVED** [review]

**Pull request merged**
