### PR TITLE
Outputs App Bundle on macOS

### PR DESCRIPTION
**Pull request by ultimaweapon**
First step of #74. Things that are still missing:

- The kernel binary.
- Qt.

### CODE REVIEW

**Comment by VocalFan** [comment]
Isn't our organization name OBHQ?

**Comment by ultimaweapon** [comment]
Sorry I don't understand your question.

**Comment by VocalFan** [comment]
Ignore me, Github Mobile formatting sucks for code lol.

**Review by bayedieng — APPROVED** [review]

**Comment by VocalFan** [comment]
@bayedieng Gonna have to wait for the PR to be updated then approve it again.

**Pull request merged**
