### PR TITLE
Add MacOS build files.

### LINKED ISSUE #74: Produce app bundled for macOS on CI
So macOS users do not need to build from sources.

### PR DESCRIPTION
**Pull request by Mou-Ikkai**
Adds release files for MacOS, also fixed CMake caching path as its different than Linux.

Should fix #74

### CODE REVIEW

**Review by ultimaweapon — CHANGES_REQUESTED** [review]
Nah it is more complicated than this. Take a look here for what is an App bundled on macOS: https://en.wikipedia.org/wiki/Bundle_(macOS)

**Comment by bayedieng** [comment]
I myself, am not quite familiar with MacOS app bundling but do know some sort of certification from Apple for an official you could have an uncertified build and allow it in security settings as an end-user like @Mou-Ikkai did but I'm guessing we want certified builds. Certifying the binary requires signing into Apple so I'm not sure how that's going to work.

**Comment by ultimaweapon** [comment]
We cannot have a signed version for now because it need some money... so let's do an unsigned version for now until we are at the stage to open for a donation.

**Comment by ultimaweapon** [comment]
This should be a good starting point: https://stackoverflow.com/questions/53560288/how-to-create-a-macos-app-bundle-with-cmake

**Pull request closed without merging**
