### PR TITLE
Restructures execution engine

### LINKED ISSUE #394: Failed to allocate 16384: Attempt to access invalid address. (os error 487).
```
++++++++++++++++++ I [00:00:00:00:952]:0x0000000000002090:kernel\src\syscalls\mod.rs:69
Syscall called: 477
++++++++++++++++++ I [00:00:00:00:952]:0x0000000000002090:kernel\src\syscalls\mod.rs:522
Guard page has been requested for main stack.
++++++++++++++++++ I [00:00:00:00:952]:0x0000000000002090:kernel\src\syscalls\mod.rs:69
Syscall called: 466
++++++++++++++++++ I [00:00:00:00:952]:0x0000000000002090:kernel\src\syscalls\mod.rs:69
Syscall called: 477
++++++++++++++++++ P [00:00:00:00:952]:0x0000000000002090:kernel\src\memory\mod.rs:322
Failed to allocate 16384: Attempt to access invalid address. (os error 487).
```

### PR DESCRIPTION
**Pull request by ultimaweapon**
Also fixes #394.

### CODE REVIEW

**Comment by VocalFan** [comment]
So... Where do syscalls get called from now?

**Comment by VocalFan** [comment]
#397 :P

**Comment by ultimaweapon** [comment]
Are there any warnings?

**Comment by VocalFan** [comment]
Only three
 
```
++++++++++++++++++ I [00:00:00:01:064]:0x00000000000072c0:kernel\src\ee\native\mod.rs:305
Syscall called: 610
++++++++++++++++++ W [00:00:00:01:064]:0x00000000000072c0:kernel\src\ee\native\mod.rs:315
Syscall 610 failed: no such file or directory.
++++++++++++++++++ I [00:00:00:01:064]:0x00000000000072c0:kernel\src\ee\native\mod.rs:305
Syscall called: 598
++++++++++++++++++ I [00:00:00:01:064]:0x00000000000072c0:kernel\src\ee\native\mod.rs:305
Syscall called: 532
++++++++++++++++++ W [00:00:00:01:064]:0x00000000000072c0:kernel\src\regmgr\mod.rs:80
regmgr_call(25) failed: entry SCE_REGMGR_ENT_KEY_DEVENV_TOOL_game_intmem_dbg not found.
```
And
```
++++++++++++++++++ I [00:00:00:01:066]:0x00000000000072c0:kernel\src\ee\native\mod.rs:305
Syscall called: 477
++++++++++++++++++ W [00:00:00:01:066]:0x00000000000072c0:kernel\src\memory\mod.rs:540
mmap(0x200000000, 0x4000, CPU_READ | CPU_WRITE, MAP_ANON, -1, 0) was success with 0x26b924c0000 instead of 0x200000000.
++++++++++++++++++ I [00:00:00:01:066]:0x00000000000072c0:kernel\src\ee\native\mod.rs:305
Syscall called: 588
++++++++++++++++++ I [00:00:00:01:066]:0x00000000000072c0:kernel\src\memory\mod.rs:569
Setting name for 0x26b924c0000:0x26b924c4000 to 'SceKernelPrimaryTcbTls'.
++++++++++++++++++ I [00:00:00:01:066]:0x00000000000072c0:kernel\src\ee\native\mod.rs:305
Syscall called: 165
++++++++++++++++++ I [00:00:00:01:066]:0x00000000000072c0:kernel\src\process\mod.rs:339
Bypassing Unimplemented Syscall as 0
```
For which as you know, 165 is the end until it gets implemented.

Also uh... Maybe change "was success with" to "was successful with"

**Review by bayedieng — APPROVED** [review]

**Pull request merged**
