### PR TITLE
Fix unused initializations from Sysinfo

### LINKED ISSUE #451: Find a solution to disable sysinfo from spawing rayon thread
Because spawning multiple threads just for this is too much. If it is not possible we need to find the other crate.

### PR DESCRIPTION
**Pull request by VocalFan**
Using New_With_Specifics instead of just New, we now only initialize the CPU and RAM sysinfo, along with disabling the spam of threads. This takes us from 30 threads back to 5 threads!

Fixes #451 

@ultimaweapon

### CODE REVIEW

**Comment by ultimaweapon** [comment]
Wait, it is still spawning the threads?

**Comment by VocalFan** [comment]
> Wait, it is still spawning the threads?

Uh, I just said the total thread the debugger shows when running the kernel. Before, it was 30 total threads. Now there's just 8 threads... Idk how many the kernel usually has.

**Comment by ultimaweapon** [comment]
You can test by setting a breakpoint at https://github.com/obhq/obliteration/blob/main/src/kernel/src/main.rs#L121. Look at the number of threads then step over it to see if it spawn another threads.

**Comment by VocalFan** [comment]
> You can test by setting a breakpoint at https://github.com/obhq/obliteration/blob/main/src/kernel/src/main.rs#L121. Look at the number of threads then step over it to see if it spawn another threads.

Seems like it spawns 3.

*Deleting all sysinfo leaves 5 threads, but adding back sysinfo leaves 8 threads on crash.*

I'm trying to see if Init system with specifics can reduce the thread count.

**Comment by VocalFan** [comment]
ALRIGHT, so, I got it so that we use `System::new_with_specifics` instead of `System::new`

**Review by ultimaweapon — APPROVED** [review]

**Pull request merged**
