### PR TITLE
Finishes regmgr_call(24)

### PR DESCRIPTION
**Pull request by ultimaweapon**

### CODE REVIEW

**Comment by ultimaweapon** [comment]
@gandalfthewhite19890404 can you test this?

**Comment by VocalFan** [comment]
https://www.psdevwiki.com/ps4/Talk:Registry

**Comment by gandalfthewhite19890404** [comment]
> @gandalfthewhite19890404 can you test this?

```
Starting application.
++++++++++++++++++ W [00:00:00:00:073]:0x0000000000002020:kernel\src\syscalls\mod.rs:94
Syscall 610 failed: no such file or directory.
++++++++++++++++++ W [00:00:00:00:073]:0x0000000000002020:kernel\src\syscalls\mod.rs:265
regmgr_call(25) was failed with 0x800d0203.
++++++++++++++++++ I [00:00:00:00:073]:0x0000000000002020:kernel\src\syscalls\mod.rs:244
Setting 0x2c30100 to 0.
++++++++++++++++++ W [00:00:00:00:073]:0x0000000000002020:kernel\src\syscalls\mod.rs:265
regmgr_call(24) was failed with 0x0.
++++++++++++++++++ I [00:00:00:00:073]:0x0000000000002020:kernel\src\syscalls\mod.rs:244
Setting 0x2c30200 to 0.
++++++++++++++++++ W [00:00:00:00:073]:0x0000000000002020:kernel\src\syscalls\mod.rs:265
regmgr_call(24) was failed with 0x0.
++++++++++++++++++ P [00:00:00:00:073]:0x0000000000002020:kernel\src\syscalls\mod.rs:87
not yet implemented: syscall 557 at 0x0000000000001afa on /system/common/lib/libkernel.sprx
```

**Comment by ultimaweapon** [comment]
@gandalfthewhite19890404 thanks!

**Review by bayedieng — APPROVED** [review]

**Pull request merged**
