### PR TITLE
Adds Actions to automatically add/remove S-ready from PRs

### PR DESCRIPTION
**Pull request by ultimaweapon**

### CODE REVIEW

**Comment by VocalFan** [comment]
I get the last one being Build-out-of-date, but what is this one?

**Comment by ultimaweapon** [comment]
The previous one has some flaws so we will move to this one instead.

**Comment by SuchAFuriousDeath** [comment]
I've been preliminarily looking at how IPC sockets work, and it looks like it's a looooot of code.

**Comment by SuchAFuriousDeath** [comment]
From the looks of it, sys_connect binds IPC sockets to a filesystem path.

**Comment by SuchAFuriousDeath** [comment]
I think socket protocols and address families could (theoretically) be generalized in a nice way, roughly like this. Hopefully we get to do this one day. 
image

**Comment by SuchAFuriousDeath** [comment]
Actually more like this:
image

**Comment by ultimaweapon** [comment]
It is likely needed to be a trait object so the trait needs to be object safe. BTW better to create a discussion instead of hooking into a random issue/PR so we can easily find it.

**Review by SuchAFuriousDeath — APPROVED** [review]

**Pull request merged**
