### PR TITLE
Initializes KVM and WHP

### PR DESCRIPTION
**Pull request by ultimaweapon**

### CODE REVIEW

**Comment by SuchAFuriousDeath** [comment]
And also, regarding the previous PR, shouldn't this be a an empty enum?
```
#[repr(C)]
pub struct hv_vm_config_t([u8; 0]);
```
Then, it can never be contructed and can only exist behind a pointer. But I'm not quite sure what your intentions were behind this.

**Comment by SuchAFuriousDeath** [comment]
llvm-sys and libc still use empty enums by the way :D

**Comment by SuchAFuriousDeath** [comment]
Is this left as draft on purpose?

**Comment by ultimaweapon** [comment]
> Is this left as draft on purpose?

Correct.

**Comment by SuchAFuriousDeath** [comment]
By the way, mikusp said on Discord that he reached sys_thr_new

**Review by SuchAFuriousDeath — APPROVED** [review]

**Pull request merged**
