### PR TITLE
Implements syscall 532

### LINKED ISSUE #323: Unimplemented Syscall 532
```
++++++++++++++++++ P [00:00:00:00:027]:0x00000000000056d0:kernel\src\syscalls\mod.rs:67
not yet implemented: syscall 532 at 0x00000000000017fa on /system/common/lib/libkernel.sprx
```

CUSTOM PS4 SYSCALL
<html>
<body>

Syscall ID | PS4 FW Version | Syscall name | Syscall usermode prototype
-- | -- | -- | --
532 | <=1.76? | sys_regmgr_call | ?

</body>
</html>

<details>
  <summary>
    Function Code:
  </summary>
  <code>__int64 __usercall sys_regmgr_call@<rax>(__int64 a1@<rdi>, __int64 a2@<rsi>, __int64 a3@<r12>, _QWORD *a4@<r13>, __int64 a5@<r15>, double a6@<xmm0>)
{
  signed int v6; // eax
  signed int v7; // eax
  signed __int64 v8; // rax
  signed __int64 v9; // rax
  __int64 v10; // rcx
  __int64 v11; // r8
  __int64 v12; // r9
  __int64 v13; // rcx
  __int64 v14; // r8
  __int64 v15; // r9
  __int64 v16; // r8
  __int64 v17; // r9
  __int64 result; // rax
  unsigned __int64 v19; // [rsp+80h] [rbp-8B0h]
  char *v20; // [rsp+C8h] [rbp-868h]
  unsigned int v21; // [rsp+D0h] [rbp-860h]
  signed int v22; // [rsp+D4h] [rbp-85Ch]
  signed int v23; // [rsp+D4h] [rbp-85Ch]
  signed int v24; // [rsp+D4h] [rbp-85Ch]
  signed int v25; // [rsp+D4h] [rbp-85Ch]
  signed int v26; // [rsp+D4h] [rbp-85Ch]
  signed int v27; // [rsp+D4h] [rbp-85Ch]
  char *v28; // [rsp+D8h] [rbp-858h]
  unsigned __int64 v29; // [rsp+E0h] [rbp-850h]
  char *v30; // [rsp+E8h] [rbp-848h]
  unsigned int v31; // [rsp+F0h] [rbp-840h]
  unsigned int v32; // [rsp+F4h] [rbp-83Ch]
  int v33; // [rsp+10Ch] [rbp-824h]
  char *v34; // [rsp+110h] [rbp-820h]
  int v35; // [rsp+118h] [rbp-818h]
  int v36; // [rsp+11Ch] [rbp-814h]
  unsigned __int64 v37; // [rsp+120h] [rbp-810h]
  __int64 v38; // [rsp+128h] [rbp-808h]
  __int64 v39; // [rsp+928h] [rbp-8h]
  v32 = *(_DWORD *)a2;
  v31 = *(_DWORD *)(a2 + 8);
  v30 = *(char **)(a2 + 24);
  v29 = *(_QWORD *)(a2 + 32);
  v28 = *(char **)(a2 + 16);
  v20 = 0LL;
  v21 = priv_check(a1, 0x2AAu);
  if ( v21 )
  {
    if ( v32 > 0x2FuLL || (v8 = 211108363239424LL, !_bittest64(&v8, v32)) )
    {
      printf((unsigned __int64)"[REGMGR] (%d): ");
      printf((unsigned __int64)"Non system process... (%08x(%08x) = %08x)\n");
      goto LABEL_222;
    }
  }
  else if ( (unsigned int)sceSblACMgrIsDecidProcess(*(_QWORD *)(a1 + 304)) == 1 )
  {
    if ( v32 > 0xC )
      goto LABEL_226;
    v6 = 980;
    if ( _bittest(&v6, v32) )
    {
      v33 = sub_FFFFFFFF826A4680(v31, 1);
      goto LABEL_12;
    }
    v7 = 42;
    if ( _bittest(&v7, v32) )
    {
      v33 = sub_FFFFFFFF826A4680(v31, 2);
      goto LABEL_12;
    }
    if ( v32 == 12 )
      v33 = 0;
    else
LABEL_226:
      v33 = -2146631144;
LABEL_12:
    if ( v33 )
      goto LABEL_219;
    goto LABEL_19;
  }
LABEL_19:
  v33 = regMgrComCheckAddr((__int64)v28);
  if ( !v33 )
  {
    if ( !(unsigned int)regMgrComCheckAddr((__int64)v30)
      || v32 <= 0x36uLL && (v9 = 21091368927911937LL, _bittest64(&v9, v32)) )
    {
      if ( v29 > 0x800 )
      {
        if ( v32 != 26 && v32 != 27 && v32 != 28 && v32 != 29 )
        {
          if ( v32 != 15 && v32 != 16 && v32 != 40 && v32 != 44 && v32 != 46 && v32 != 47 )
          {
            v33 = -2146631160;
            goto LABEL_219;
          }
        }
        else if ( v29 > 0x818 )
        {
          v33 = -2146631160;
          goto LABEL_219;
        }
      }
      sub_FFFFFFFF8269C7E0((char *)&v34, 0, 0x818uLL);
      switch ( (unsigned __int64)v32 )
      {
        case 0uLL:
          v33 = sceRegMgrGetVersion(a3, a4, a5, a6);
          break;
        case 1uLL:
          if ( (unsigned int)copyin(v30, (char *)&v34, 4uLL) )
            v33 = -2146631153;
          else
            v33 = sceRegMgrSetInt(v31, (int)v34, a3, a4, a5, a6);
          break;
        case 2uLL:
          v33 = sceRegMgrGetInt(v31, (char *)&v34, a3, a4, a5, a6);
          if ( !v33 )
          {
            v33 = copyout((char *)&v34, v30, 4uLL);
            if ( v33 )
              v33 = -2146631152;
          }
          break;
        case 3uLL:
          if ( (unsigned int)copyin(v30, (char *)&v34, v29) )
            v33 = -2146631153;
          else
            v33 = sceRegMgrSetStr(v29, v31, (unsigned __int8 *)&v34, a3, a4, a5, a6);
          break;
        case 4uLL:
          v33 = sceRegMgrGetStr(v29, v31, (char *)&v34, a3, a4, a5, a6);
          if ( !v33 )
          {
            v33 = copyout((char *)&v34, v30, v29);
            if ( v33 )
              v33 = -2146631152;
          }
          break;
        case 5uLL:
          if ( (unsigned int)copyin(v30, (char *)&v34, v29) )
            v33 = -2146631153;
          else
            v33 = sceRegMgrSetBin(v29, v31, (unsigned __int8 *)&v34, a3, a4, a5, a6);
          break;
        case 6uLL:
          v33 = sceRegMgrGetBin(v29, v31, (char *)&v34, a3, a4, a5, a6);
          if ( !v33 )
          {
            v33 = copyout((char *)&v34, v30, v29);
            if ( v33 )
              v33 = -2146631152;
          }
          break;
        case 7uLL:
          v33 = sceRegMgrGetIntInitVal(v31, &v34, a3, a4, a5, a6);
          if ( !v33 )
          {
            v33 = copyout((char *)&v34, v30, 4uLL);
            if ( v33 )
              v33 = -2146631152;
          }
          break;
        case 8uLL:
          v33 = sceRegMgrGetStrInitVal(v29, v31, (char *)&v34, a3, a4, a5, a6);
          if ( !v33 )
          {
            v33 = copyout((char *)&v34, v30, v29);
            if ( v33 )
              v33 = -2146631152;
          }
          break;
        case 9uLL:
          v33 = sceRegMgrGetBinInitVal(v29, v31, (char *)&v34, a3, a4, a5, a6);
          if ( !v33 )
          {
            v33 = copyout((char *)&v34, v30, v29);
            if ( v33 )
              v33 = -2146631152;
          }
          break;
        case 0xAuLL:
          if ( (unsigned int)copyin(v30, (char *)&v34, 4uLL) )
            v33 = -2146631153;
          else
            v33 = sceRegMgrSetInitLevel((unsigned int)v34, a3, a4, a5, a6);
          break;
        case 0xBuLL:
          if ( (unsigned int)copyin(v30, (char *)&v34, 4uLL) )
            v33 = -2146631153;
          else
            v33 = sceRegMgrResetVal(v31, (unsigned int)v34, a3, a4, a5, a6);
          break;
        case 0xCuLL:
        case 0x1EuLL:
          if ( (unsigned int)copyin(v30, (char *)&v34, 4uLL) )
            v33 = -2146631153;
          else
            v33 = sceRegMgrCheckError((signed int)v34);
          break;
        case 0xDuLL:
          v33 = sceRegMgrPrivateStorageCount(v31, a3, a4, a5, a6);
          break;
        case 0xEuLL:
          v33 = sceRegMgrPrivateStorageMeasure(v31);
          break;
        case 0xFuLL:
        case 0x10uLL:
          if ( sceRegMgrPrivateStorageMeasure(v31) == v29 )
          {
            v20 = malloc(v29, (__int64)&M_REGMGR, 257, v13, v14, v15, a6, a3);
            if ( v20 )
            {
              if ( v32 == 15 )
              {
                if ( (unsigned int)copyin(v30, v20, v29) )
                  v33 = -2146631153;
                else
                  v33 = sceRegMgrPrivateStorageInject(v31, v20, v29);
              }
              else
              {
                v33 = sceRegMgrPrivateStorageRead(v29, v31, v20, a3, a4, a5, a6);
                if ( !v33 )
                {
                  v33 = copyout(v20, v30, v29);
                  if ( v33 )
                    v33 = -2146631152;
                }
              }
            }
            else
            {
              v33 = -2146631151;
            }
          }
          else
          {
            v33 = -2146631160;
          }
          break;
        case 0x11uLL:
          v33 = sceRegMgrPrivateStorageStart(a3, a4, a5);
          break;
        case 0x12uLL:
          v33 = sceRegMgrSrvGetRegion(a3, a4, a5, a6);
          break;
        case 0x13uLL:
          v33 = sceRegMgrSrvGetRegionStr((char *)&v34, v29, a3, a4, a5, a6);
          if ( v33 >= 1 )
          {
            v33 = copyout((char *)&v34, v30, v29);
            if ( v33 )
              v33 = -2146631152;
          }
          break;
        case 0x14uLL:
          v33 = sceRegMgrSrvCnvRegionStr(v29, v31, (char *)&v34, a3, a4, a5, a6);
          if ( !v33 )
          {
            v33 = copyout((char *)&v34, v30, v29);
            if ( v33 )
              v33 = -2146631152;
          }
          break;
        case 0x15uLL:
          if ( (unsigned int)copyin(v30, (char *)&v34, 0x800uLL) )
            v33 = -2146631153;
          else
            v33 = sceRegMgrSrvCnvRegionInt((unsigned __int8 *)&v34, a3, a4, a5, a6);
          break;
        case 0x16uLL:
          v33 = sceRegMgrSrvGetMachineType(a3, a4, a5, a6);
          break;
        case 0x17uLL:
          v33 = sceRegMgrSrvGetQAFforReg(a3, a4, a5, a6);
          break;
        case 0x18uLL:
          v33 = copyin(v30, (char *)&v34, 0x10uLL);
          if ( v33 )
          {
            v33 = -2146631153;
          }
          else
          {
            v22 = sub_FFFFFFFF826A4750((__int64)v34, v35, *(_QWORD *)(a1 + 304), 2);
            if ( v22 > 0 )
              v33 = sceRegMgrSetInt(v22, v36, a3, a4, a5, a6);
            else
              v33 = v22;
          }
          break;
        case 0x19uLL:
          v33 = copyin(v30, (char *)&v34, 0x10uLL);
          if ( v33 )
          {
            v33 = -2146631153;
          }
          else
          {
            v23 = sub_FFFFFFFF826A4750((__int64)v34, v35, *(_QWORD *)(a1 + 304), 1);
            if ( v23 > 0 )
            {
              v33 = sceRegMgrGetInt(v23, (char *)&v36, a3, a4, a5, a6);
              if ( !v33 )
              {
                v33 = copyout((char *)&v34, v30, 0x10uLL);
                if ( v33 )
                  v33 = -2146631152;
              }
            }
            else
            {
              v33 = v23;
            }
          }
          break;
        case 0x1AuLL:
          v33 = copyin(v30, (char *)&v34, 0x818uLL);
          if ( v33 )
          {
            v33 = -2146631153;
          }
          else
          {
            v24 = sub_FFFFFFFF826A4750((__int64)v34, v35, *(_QWORD *)(a1 + 304), 2);
            if ( v24 > 0 )
              v33 = sceRegMgrSetStr(v37, v24, (unsigned __int8 *)&v38, a3, a4, a5, a6);
            else
              v33 = v24;
          }
          break;
        case 0x1BuLL:
          v33 = copyin(v30, (char *)&v34, 0x818uLL);
          if ( v33 )
          {
            v33 = -2146631153;
          }
          else
          {
            v25 = sub_FFFFFFFF826A4750((__int64)v34, v35, *(_QWORD *)(a1 + 304), 1);
            if ( v25 > 0 )
            {
              v33 = sceRegMgrGetStr(v37, v25, (char *)&v38, a3, a4, a5, a6);
              if ( !v33 )
              {
                v33 = copyout((char *)&v34, v30, 0x818uLL);
                if ( v33 )
                  v33 = -2146631152;
              }
            }
            else
            {
              v33 = v25;
            }
          }
          break;
        case 0x1CuLL:
          v33 = copyin(v30, (char *)&v34, 0x818uLL);
          if ( v33 )
          {
            v33 = -2146631153;
          }
          else
          {
            v26 = sub_FFFFFFFF826A4750((__int64)v34, v35, *(_QWORD *)(a1 + 304), 2);
            if ( v26 > 0 )
              v33 = sceRegMgrSetBin(v37, v26, (unsigned __int8 *)&v38, a3, a4, a5, a6);
            else
              v33 = v26;
          }
          break;
        case 0x1DuLL:
          v33 = copyin(v30, (char *)&v34, 0x818uLL);
          if ( v33 )
          {
            v33 = -2146631153;
          }
          else
          {
            v27 = sub_FFFFFFFF826A4750((__int64)v34, v35, *(_QWORD *)(a1 + 304), 1);
            if ( v27 > 0 )
            {
              v33 = sceRegMgrGetBin(v37, v27, (char *)&v38, a3, a4, a5, a6);
              if ( !v33 )
              {
                v33 = copyout((char *)&v34, v30, 0x818uLL);
                if ( v33 )
                  v33 = -2146631152;
              }
            }
            else
            {
              v33 = v27;
            }
          }
          break;
        case 0x1FuLL:
        case 0x21uLL:
          v20 = malloc(v29, (__int64)&M_REGMGR, 257, v10, v11, v12, a6, a3);
          if ( v20 )
          {
            if ( v32 == 31 )
              v33 = sceRegMgrPrivateStorageFileName(v31, v20, v29);
            else
              v33 = sceRegMgrPrivateStorageDirName(v31, v20, v29);
            if ( !v33 )
            {
              v33 = copyout(v20, v30, v29);
              if ( v33 )
                v33 = -2146631152;
            }
          }
          else
          {
            v33 = -2146631151;
          }
          break;
        case 0x20uLL:
          v33 = sceRegMgrPrivateStorageDirCount();
          break;
        case 0x22uLL:
          v33 = sceRegMgrPrivateStorageDirPermit(v31);
          break;
        case 0x23uLL:
          v33 = sceRegMgrSyncHdd(a3, a4, a5, a6);
          break;
        case 0x24uLL:
          v33 = sceRegMgrSrvGetRealMachineType(a3, a4, a5, a6);
          break;
        case 0x25uLL:
          v33 = sceRegMgrToolGetUpdateCnt();
          break;
        case 0x26uLL:
          v33 = sceRegMgrToolGetEntryCnt();
          break;
        case 0x28uLL:
        case 0x2CuLL:
          if ( v29 == 2072 )
          {
            if ( (unsigned int)copyin(v30, (char *)&v34, 0x818uLL) )
            {
              v33 = -2146631153;
            }
            else
            {
              if ( v32 == 44 )
                v33 = sceRegMgrDrvDataCheckGet(v31, (__int64)&v34);
              else
                v33 = sceRegMgrToolDataCheckGet(v31, (__int64)&v34);
              if ( !v33 )
              {
                v33 = copyout((char *)&v34, v30, 0x818uLL);
                if ( v33 )
                  v33 = -2146631152;
              }
            }
          }
          else
          {
            v33 = -2146631160;
          }
          break;
        case 0x29uLL:
          v33 = sceRegMgrDrvGetUpdateCnt();
          break;
        case 0x2AuLL:
          v33 = sceRegMgrDrvGetEntCnt();
          break;
        case 0x2BuLL:
          v33 = sceRegMgrDrvDataOpen(a4, a6);
          break;
        case 0x2DuLL:
          v33 = sceRegMgrDrvDataClose(a3, (__int64)a4, a5, a6);
          break;
        case 0x2EuLL:
          v33 = sceRegMgrLogStart();
          break;
        case 0x2FuLL:
          if ( !v30 )
            goto LABEL_213;
          v20 = malloc(v29, (__int64)&M_REGMGR, 257, v10, v11, v12, a6, a3);
          if ( v20 )
          {
            sub_FFFFFFFF8269C7E0(v20, 0, v29);
LABEL_213:
            v33 = sceRegMgrLogPull();
            if ( !v33 )
            {
              if ( v30 )
              {
                v33 = copyout(v20, v30, v29);
                if ( v33 )
                  v33 = -2146631152;
              }
            }
          }
          else
          {
            v33 = -2146631151;
          }
          break;
        case 0x30uLL:
          if ( (unsigned int)copyin(v30, (char *)&v34, 4uLL) )
            v33 = -2146631153;
          else
            v33 = sceRegMgrIsChange(v31, (int)v34, a3, a4, a5, a6);
          break;
        case 0x31uLL:
          v33 = sceRegMgrEvtGetCnt(v31);
          break;
        case 0x32uLL:
          if ( (unsigned int)copyin(v30, (char *)&v34, 4uLL) )
            v33 = -2146631153;
          else
            v33 = sceRegMgrEvtGetRegId(v31, (int)v34);
          break;
        case 0x33uLL:
          v33 = sceRegMgrBackupNeedMem(v31);
          break;
        case 0x34uLL:
        case 0x35uLL:
          if ( (unsigned int)copyin(v30, (char *)&v34, 0x18uLL) )
          {
            v33 = -2146631153;
          }
          else if ( (unsigned int)regMgrComCheckAddr((__int64)v34) )
          {
            v33 = -2146631166;
          }
          else
          {
            v19 = *(_QWORD *)&v35;
            v20 = malloc(*(unsigned __int64 *)&v35, (__int64)&M_REGMGR, 257, 0LL, v16, v17, a6, a3);
            if ( v20 )
            {
              if ( v32 == 53 )
              {
                if ( (unsigned int)copyin(v34, v20, v19) )
                  v33 = -2146631153;
                else
                  v33 = sceRegMgrBackupPushData(v37, (__int64)v20, v19, a3, a4, a5, a6);
              }
              else if ( sceRegMgrBackupNeedMem(v37) == v19 )
              {
                v33 = sceRegMgrBackupPullData(v37, (__int64)v20, v19, a3, a4, a5, a6);
                if ( !v33 )
                {
                  v33 = copyout(v20, v34, v19);
                  if ( v33 )
                    v33 = -2146631152;
                }
              }
              else
              {
                v33 = -2146631160;
              }
            }
            else
            {
              v33 = -2146631151;
            }
          }
          break;
        case 0x36uLL:
          v33 = sceRegMgrPrivateStorageIsNvsChange();
          break;
        default:
          v33 = -2146631143;
          break;
      }
    }
    else
    {
      v33 = -2146631166;
    }
  }
LABEL_219:
  if ( v20 )
    free((unsigned __int64)v20, (__int64)&M_REGMGR, (__int64)a4, a6, a5);
  v21 = copyout((char *)&v33, v28, 4uLL);
LABEL_222:
  result = v21;
  if ( _stack_chk_guard == v39 )
    result = v21;
  return result;
}
</code>
</details>

### PR DESCRIPTION
**Pull request by ultimaweapon**
Fixes #323.

### CODE REVIEW

**Comment by VocalFan** [comment]
I'll test when I get home.

**Comment by gandalfthewhite19890404** [comment]
Now for Sonic:
```
++++++++++++++++++ W [00:00:00:00:063]:0x0000000000001af4:kernel\src\syscalls\mod.rs:94
Syscall 610 failed: no such file or directory.
++++++++++++++++++ P [00:00:00:00:063]:0x0000000000001af4:kernel\src\syscalls\mod.rs:246
not yet implemented: regmgr_call with type = 24
```

**Comment by ultimaweapon** [comment]
@gandalfthewhite19890404 could you create an issue for this?

**Comment by VocalFan** [comment]
All 9/9 apps reach #293

**Pull request merged**
