### PR TITLE
Revises FS mount

### PR DESCRIPTION
**Pull request by ultimaweapon**
So it will be more idiomatic Rust than C.

### CODE REVIEW

**Comment by SuchAFuriousDeath** [comment]
I actually think the MountOps should be an enum like
`rust
enum MountOpts {
HostFs(HostFsMountOpts),
Devfs(DevfsMountOpts)
...
}
` 
Having it this way would make it impossible to forget an option or provide one that isn't accepted by the FS. Also, we could get rid of all the unwraps, readability +1000. What do you think?

**Comment by ultimaweapon** [comment]
> I actually think the MountOps should be an enum like `enum MountOpts { HostFs(HostFsMountOpts), Devfs(DevfsMountOpts) ... }` Having it this way would make it impossible to forget an option or provide one that isn't accepted by the FS. Also, we could get rid of all the unwraps, readability +1000. What do you think? I can refactor it in my PR.

The problem is mount options usually passed from the user as a string. That mean we need some mechanism to parse it from the string. I think your current solution is nullfs is good enough unless we find a better than that.

**Comment by SuchAFuriousDeath** [comment]
Oh, ok. The mount data could easily be an enum though, right?

**Review by SuchAFuriousDeath — APPROVED** [review]

**Comment by ultimaweapon** [comment]
> Oh, ok. The mount data could easily be an enum though, right?

It could but I don't think it is better than `Any` in this case. Trait object should be the right solution here.

**Comment by ultimaweapon** [comment]
Something like this:

```rust
struct Mount {
    data: Arch<dyn Filesystem>,
}

trait Filesystem {}
```

**Comment by ultimaweapon** [comment]
Actually I already tried something like that with this PR but found out it is a massive changes so I decided to revert it otherwise you are going to have a big problem with your nullfs PR.

**Pull request merged**
