### PR TITLE
Implements regmgr_call request decoder with v2 = 0

### LINKED ISSUE #344: Unimplemented - decode regmgr_call request with v2 = 0
```
++++++++++++++++++ P [00:00:00:00:080]:0x00000000000001fc:kernel\src\regmgr\mod.rs:72
not yet implemented: decode regmgr_call request with v2 = 0
```

### PR DESCRIPTION
**Pull request by ultimaweapon**
Fixes #344.

### CODE REVIEW

**Comment by VocalFan** [comment]
Implementing v2 = 0 was easier than you thought, huh?

**Comment by ultimaweapon** [comment]
@gandalfthewhite19890404 can you test this?

**Comment by VocalFan** [comment]
Well, I'm in boredom, so anything for me to do?

**Comment by gandalfthewhite19890404** [comment]
> @gandalfthewhite19890404 can you test this?

++++++++++++++++++ P [00:00:00:00:097]:0x0000000000001364:kernel\src\syscalls\mod.rs:244
not yet implemented: regmgr_call(24) with matched key = 0x2c30100

**Comment by VocalFan** [comment]
Can't think of anything to add to the UI rn... If ya have suggestions lmk, even if they're just minor.

**Review by bayedieng — APPROVED** [review]

**Pull request merged**
