### PR TITLE
Add guide on how to get the firmware file in README

### PR DESCRIPTION
**Pull request by ArbestRi**
Referenced from https://github.com/obhq/obliteration/issues/20. Suggested changes are welcome. No longer a rough tutorial

### CODE REVIEW

**Comment by gandalfthewhite19890404** [comment]
Hello!
Did you tested it?
I did with FW 9.00- it does not works, there are an issue in repository - https://github.com/ultimaweapon/ps4-update-decryptor/issues/1

**Comment by ultimaweapon** [comment]
Thanks for the PR. The problem is @gandalfthewhite19890404 just tested the descriptor and it does not work. Not sure if it works for you.

**Comment by ArbestRi** [comment]
fewafdeszsd

**Comment by ArbestRi** [comment]
Also, I can't see if it works for myself since
my PS4 is on a non-jailbreakable firmware (10.01).

**Pull request closed without merging**
