### PR TITLE
Add errnos 95-99

### PR DESCRIPTION
**Pull request by VocalFan**
Looked at the PS4 error code viewer to get the 5 sony-specific implemented Errnos, and if you really want me to identify the numbers:

```
aSceKernelError_94         // "SCE_KERNEL_ERROR_ECAPMODE"
aSceKernelError_95         // "SCE_KERNEL_ERROR_ENOBLK"
aSceKernelError_96         // "SCE_KERNEL_ERROR_EICV"
aSceKernelError_97         // "SCE_KERNEL_ERROR_ENOPLAYGOENT"
aSceKernelError_98         // "SCE_KERNEL_ERROR_EREVOKE"
aSceKernelError_99         // "SCE_KERNEL_ERROR_ESDKVERSION"
```

### CODE REVIEW

**Comment by ultimaweapon** [comment]
What is a PS4 error code viewer? Is it the official SDK tool from Sony?

**Comment by VocalFan** [comment]
> What is a PS4 error code viewer? Is it the official SDK tool from Sony?

Not technically part of the SDK, but from Sony, yeah.

**Comment by ultimaweapon** [comment]
> but from Sony

What do you mean?

**Comment by VocalFan** [comment]
> > but from Sony
> 
> What do you mean?

*Jk, apparently it is part of the SDK.*

image

**Comment by ultimaweapon** [comment]
Where do you get those numbers? 1E3 is not equal to 95.

**Comment by VocalFan** [comment]
Seeing as it says SceKernelError_96 on there

**Comment by VocalFan** [comment]
> Where do you get those numbers? 1E3 is not equal to 95.

You're looking at the wrong spot lol. Look at the end of 0x800200XX
0x80020060 -> 0x60 -> 96, which matches EICV's name. "aSceKernelError_96"

**Review by ultimaweapon — APPROVED** [review]

**Pull request merged**
