### PR TITLE
Implements syscall 5

### LINKED ISSUE #369: Unimplemented Syscall 5
Syscall 5, also known as [open](https://man.freebsd.org/cgi/man.cgi?query=open&apropos=0&sektion=2&manpath=FreeBSD+9.1-RELEASE&arch=default&format=html)

The source code is here: https://cgit.freebsd.org/src/tree/sys/kern/vfs_syscalls.c?h=releng/9.1#n1038

### PR DESCRIPTION
**Pull request by ultimaweapon**
Fixes #369.

### CODE REVIEW

**Comment by VocalFan** [comment]
Games now reach #370 But uh, where the heck is /dev/console/ created? Haha

**Comment by ultimaweapon** [comment]
https://en.wikipedia.org/wiki/Device_file

**Comment by VocalFan** [comment]
> https://en.wikipedia.org/wiki/Device_file

Oh, it's literally just the windows equivalent of the CON file?

**Comment by ultimaweapon** [comment]
Not actually. You can access the hardware via a device file like HDD on *nix from user space. This is not possible on Windows.

**Review by bayedieng — APPROVED** [review]

**Pull request merged**
