### PR TITLE
Implements device ioctl

### PR DESCRIPTION
**Pull request by SuchAFuriousDeath**

### CODE REVIEW

**Comment by SuchAFuriousDeath** [comment]
Just as a sidenote, with a couple of half-assed implemetations, I'm already able to reach 
image

**Comment by SuchAFuriousDeath** [comment]
We currently crash on this, after loading so many libraries that all the outputted text doesn't fit inside the terminal

image

**Comment by SuchAFuriousDeath** [comment]
We currently load
libKernel.sprx
libSceLibcInternal.sprx
libSceSysmodule.sprx
libSceDiscMap.sprx
libSceFios2.sprx
libSceNet.sprx
libSceIpmi.sprx
libSceMbus.sprx
libSceRegMgr.sprx
libSceRtc.sprx
libSceAvSetting.sprx
libSceVideoOut.sprx
libSceGnmDriver.sprx
libSceAudioOut.sprx
libSceAudioIn.sprx
libSceAjm.sprx
libScePad.sprx
libSceCamera.sprx
libSceNetCtl.sprx
libSceHttp.sprx
libSceSsl2.sprx
libSceNpCommon.sprx
libSceNpManager.sprx
libSceNpWebApi.sprx
libSceSaveData.sprx
libSceSystemService.sprx
libSceUserService.sprx
libSceCommonDialog.sprx
libSceSysUtil.sprx

I¨ve spoken with mikusp and he says that the current crash is caused by #614 (i.e. the init function of the modules aren't being ran, which also means that There's a lot of unimplemented syscalls that got skipped because of the bug)

**Comment by SuchAFuriousDeath** [comment]
After doing a temp fix, we now reach syscall 593, which there is a PR for.

**Review by mikusp — APPROVED** [review]

**Review by mikusp — APPROVED** [review]

**Pull request merged**
