### PR TITLE
Implement decitty devices

### PR DESCRIPTION
**Pull request by mikusp**

### CODE REVIEW

**Comment by ultimaweapon** [comment]
Looking good and thanks for the contribution! Could you merge the latest `main` to this so I can merge it?

**Comment by mikusp** [comment]
Thanks @ultimaweapon! I\ve pushed the rebased branch

**Comment by ultimaweapon** [comment]
@SuchAFuriousDeath can you take a look at this? I already merge the main into this so I can't be a reviewer.

**Comment by SuchAFuriousDeath** [comment]
Sure, I'll take a look when I have time

**Comment by SuchAFuriousDeath** [comment]
@ultimaweapon Merge into this branch and I'll merge it into main

**Comment by SuchAFuriousDeath** [comment]
@ultimaweapon Oops. Now it needs one more merge :sweat:

**Review by SuchAFuriousDeath — APPROVED** [review]

**Pull request merged**
